// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: services/billing/entities/v1alpha2/invoice.proto

package entitiesv1alpha2

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: Marked as deprecated in services/billing/entities/v1alpha2/invoice.proto.
type Product int32

const (
	Product_PRODUCT_UNSPECIFIED          Product = 0
	Product_PRODUCT_OMNI                 Product = 200
	Product_PRODUCT_OMNI_SEATS           Product = 201
	Product_PRODUCT_OMNI_CHAT_SENT       Product = 202
	Product_PRODUCT_OMNI_CHAT_RECEIVED   Product = 203
	Product_PRODUCT_OMNI_EMAILS_SENT     Product = 204
	Product_PRODUCT_OMNI_EMAILS_RECEIVED Product = 205
	Product_PRODUCT_OMNI_SMS_SENT        Product = 206
	Product_PRODUCT_OMNI_SMS_RECEIVED    Product = 207
	Product_PRODUCT_COMPLIANCE           Product = 300
)

// Enum value maps for Product.
var (
	Product_name = map[int32]string{
		0:   "PRODUCT_UNSPECIFIED",
		200: "PRODUCT_OMNI",
		201: "PRODUCT_OMNI_SEATS",
		202: "PRODUCT_OMNI_CHAT_SENT",
		203: "PRODUCT_OMNI_CHAT_RECEIVED",
		204: "PRODUCT_OMNI_EMAILS_SENT",
		205: "PRODUCT_OMNI_EMAILS_RECEIVED",
		206: "PRODUCT_OMNI_SMS_SENT",
		207: "PRODUCT_OMNI_SMS_RECEIVED",
		300: "PRODUCT_COMPLIANCE",
	}
	Product_value = map[string]int32{
		"PRODUCT_UNSPECIFIED":          0,
		"PRODUCT_OMNI":                 200,
		"PRODUCT_OMNI_SEATS":           201,
		"PRODUCT_OMNI_CHAT_SENT":       202,
		"PRODUCT_OMNI_CHAT_RECEIVED":   203,
		"PRODUCT_OMNI_EMAILS_SENT":     204,
		"PRODUCT_OMNI_EMAILS_RECEIVED": 205,
		"PRODUCT_OMNI_SMS_SENT":        206,
		"PRODUCT_OMNI_SMS_RECEIVED":    207,
		"PRODUCT_COMPLIANCE":           300,
	}
)

func (x Product) Enum() *Product {
	p := new(Product)
	*p = x
	return p
}

func (x Product) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Product) Descriptor() protoreflect.EnumDescriptor {
	return file_services_billing_entities_v1alpha2_invoice_proto_enumTypes[0].Descriptor()
}

func (Product) Type() protoreflect.EnumType {
	return &file_services_billing_entities_v1alpha2_invoice_proto_enumTypes[0]
}

func (x Product) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Product.Descriptor instead.
func (Product) EnumDescriptor() ([]byte, []int) {
	return file_services_billing_entities_v1alpha2_invoice_proto_rawDescGZIP(), []int{0}
}

type Invoice struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BillingCycle  string                  `protobuf:"bytes,1,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	CreateTime    *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Items         []*InvoiceItem          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	DownloadUrl   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_services_billing_entities_v1alpha2_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_entities_v1alpha2_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_services_billing_entities_v1alpha2_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *Invoice) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Invoice) GetItems() []*InvoiceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Invoice) GetDownloadUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.DownloadUrl
	}
	return nil
}

// InvoiceItem represents a single line item on an invoice.
type InvoiceItem struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Deprecated: Marked as deprecated in services/billing/entities/v1alpha2/invoice.proto.
	Product     Product                `protobuf:"varint,2,opt,name=product,proto3,enum=services.billing.entities.v1alpha2.Product" json:"product,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	// Deprecated: Marked as deprecated in services/billing/entities/v1alpha2/invoice.proto.
	Price         float64              `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Columns       []*InvoiceItemColumn `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty"`
	RatedAmount   *decimal.Decimal     `protobuf:"bytes,7,opt,name=rated_amount,json=ratedAmount,proto3" json:"rated_amount,omitempty"`
	ProductId     string               `protobuf:"bytes,8,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceItem) Reset() {
	*x = InvoiceItem{}
	mi := &file_services_billing_entities_v1alpha2_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceItem) ProtoMessage() {}

func (x *InvoiceItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_entities_v1alpha2_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceItem.ProtoReflect.Descriptor instead.
func (*InvoiceItem) Descriptor() ([]byte, []int) {
	return file_services_billing_entities_v1alpha2_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceItem) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Deprecated: Marked as deprecated in services/billing/entities/v1alpha2/invoice.proto.
func (x *InvoiceItem) GetProduct() Product {
	if x != nil {
		return x.Product
	}
	return Product_PRODUCT_UNSPECIFIED
}

func (x *InvoiceItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvoiceItem) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// Deprecated: Marked as deprecated in services/billing/entities/v1alpha2/invoice.proto.
func (x *InvoiceItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InvoiceItem) GetColumns() []*InvoiceItemColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *InvoiceItem) GetRatedAmount() *decimal.Decimal {
	if x != nil {
		return x.RatedAmount
	}
	return nil
}

func (x *InvoiceItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// InvoiceItemColumn represents a single column on an invoice item.
type InvoiceItemColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceItemColumn) Reset() {
	*x = InvoiceItemColumn{}
	mi := &file_services_billing_entities_v1alpha2_invoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceItemColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceItemColumn) ProtoMessage() {}

func (x *InvoiceItemColumn) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_entities_v1alpha2_invoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceItemColumn.ProtoReflect.Descriptor instead.
func (*InvoiceItemColumn) Descriptor() ([]byte, []int) {
	return file_services_billing_entities_v1alpha2_invoice_proto_rawDescGZIP(), []int{2}
}

func (x *InvoiceItemColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvoiceItemColumn) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_services_billing_entities_v1alpha2_invoice_proto protoreflect.FileDescriptor

const file_services_billing_entities_v1alpha2_invoice_proto_rawDesc = "" +
	"\n" +
	"0services/billing/entities/v1alpha2/invoice.proto\x12\"services.billing.entities.v1alpha2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19google/type/decimal.proto\"\xf3\x01\n" +
	"\aInvoice\x12#\n" +
	"\rbilling_cycle\x18\x01 \x01(\tR\fbillingCycle\x12;\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12E\n" +
	"\x05items\x18\x03 \x03(\v2/.services.billing.entities.v1alpha2.InvoiceItemR\x05items\x12?\n" +
	"\fdownload_url\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdownloadUrl\"\x8a\x03\n" +
	"\vInvoiceItem\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12I\n" +
	"\aproduct\x18\x02 \x01(\x0e2+.services.billing.entities.v1alpha2.ProductB\x02\x18\x01R\aproduct\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x18\n" +
	"\x05price\x18\x05 \x01(\x01B\x02\x18\x01R\x05price\x12O\n" +
	"\acolumns\x18\x06 \x03(\v25.services.billing.entities.v1alpha2.InvoiceItemColumnR\acolumns\x127\n" +
	"\frated_amount\x18\a \x01(\v2\x14.google.type.DecimalR\vratedAmount\x12\x1d\n" +
	"\n" +
	"product_id\x18\b \x01(\tR\tproductId\"=\n" +
	"\x11InvoiceItemColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*\xa7\x02\n" +
	"\aProduct\x12\x17\n" +
	"\x13PRODUCT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\fPRODUCT_OMNI\x10\xc8\x01\x12\x17\n" +
	"\x12PRODUCT_OMNI_SEATS\x10\xc9\x01\x12\x1b\n" +
	"\x16PRODUCT_OMNI_CHAT_SENT\x10\xca\x01\x12\x1f\n" +
	"\x1aPRODUCT_OMNI_CHAT_RECEIVED\x10\xcb\x01\x12\x1d\n" +
	"\x18PRODUCT_OMNI_EMAILS_SENT\x10\xcc\x01\x12!\n" +
	"\x1cPRODUCT_OMNI_EMAILS_RECEIVED\x10\xcd\x01\x12\x1a\n" +
	"\x15PRODUCT_OMNI_SMS_SENT\x10\xce\x01\x12\x1e\n" +
	"\x19PRODUCT_OMNI_SMS_RECEIVED\x10\xcf\x01\x12\x17\n" +
	"\x12PRODUCT_COMPLIANCE\x10\xac\x02\x1a\x02\x18\x01B\xb1\x02\n" +
	"&com.services.billing.entities.v1alpha2B\fInvoiceProtoP\x01ZNgithub.com/tcncloud/api-go/services/billing/entities/v1alpha2;entitiesv1alpha2\xa2\x02\x03SBE\xaa\x02\"Services.Billing.Entities.V1alpha2\xca\x02\"Services\\Billing\\Entities\\V1alpha2\xe2\x02.Services\\Billing\\Entities\\V1alpha2\\GPBMetadata\xea\x02%Services::Billing::Entities::V1alpha2b\x06proto3"

var (
	file_services_billing_entities_v1alpha2_invoice_proto_rawDescOnce sync.Once
	file_services_billing_entities_v1alpha2_invoice_proto_rawDescData []byte
)

func file_services_billing_entities_v1alpha2_invoice_proto_rawDescGZIP() []byte {
	file_services_billing_entities_v1alpha2_invoice_proto_rawDescOnce.Do(func() {
		file_services_billing_entities_v1alpha2_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_billing_entities_v1alpha2_invoice_proto_rawDesc), len(file_services_billing_entities_v1alpha2_invoice_proto_rawDesc)))
	})
	return file_services_billing_entities_v1alpha2_invoice_proto_rawDescData
}

var file_services_billing_entities_v1alpha2_invoice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_billing_entities_v1alpha2_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_billing_entities_v1alpha2_invoice_proto_goTypes = []any{
	(Product)(0),                   // 0: services.billing.entities.v1alpha2.Product
	(*Invoice)(nil),                // 1: services.billing.entities.v1alpha2.Invoice
	(*InvoiceItem)(nil),            // 2: services.billing.entities.v1alpha2.InvoiceItem
	(*InvoiceItemColumn)(nil),      // 3: services.billing.entities.v1alpha2.InvoiceItemColumn
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
	(*decimal.Decimal)(nil),        // 6: google.type.Decimal
}
var file_services_billing_entities_v1alpha2_invoice_proto_depIdxs = []int32{
	4, // 0: services.billing.entities.v1alpha2.Invoice.create_time:type_name -> google.protobuf.Timestamp
	2, // 1: services.billing.entities.v1alpha2.Invoice.items:type_name -> services.billing.entities.v1alpha2.InvoiceItem
	5, // 2: services.billing.entities.v1alpha2.Invoice.download_url:type_name -> google.protobuf.StringValue
	0, // 3: services.billing.entities.v1alpha2.InvoiceItem.product:type_name -> services.billing.entities.v1alpha2.Product
	4, // 4: services.billing.entities.v1alpha2.InvoiceItem.date:type_name -> google.protobuf.Timestamp
	3, // 5: services.billing.entities.v1alpha2.InvoiceItem.columns:type_name -> services.billing.entities.v1alpha2.InvoiceItemColumn
	6, // 6: services.billing.entities.v1alpha2.InvoiceItem.rated_amount:type_name -> google.type.Decimal
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_services_billing_entities_v1alpha2_invoice_proto_init() }
func file_services_billing_entities_v1alpha2_invoice_proto_init() {
	if File_services_billing_entities_v1alpha2_invoice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_billing_entities_v1alpha2_invoice_proto_rawDesc), len(file_services_billing_entities_v1alpha2_invoice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_billing_entities_v1alpha2_invoice_proto_goTypes,
		DependencyIndexes: file_services_billing_entities_v1alpha2_invoice_proto_depIdxs,
		EnumInfos:         file_services_billing_entities_v1alpha2_invoice_proto_enumTypes,
		MessageInfos:      file_services_billing_entities_v1alpha2_invoice_proto_msgTypes,
	}.Build()
	File_services_billing_entities_v1alpha2_invoice_proto = out.File
	file_services_billing_entities_v1alpha2_invoice_proto_goTypes = nil
	file_services_billing_entities_v1alpha2_invoice_proto_depIdxs = nil
}
