// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/v1alpha1/org/permissions.proto

package org

import (
	commons "github.com/tcncloud/api-go/api/commons"
	auth "github.com/tcncloud/api-go/api/commons/auth"
	org "github.com/tcncloud/api-go/api/commons/org"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for the GetPermissions RPC.
type GetPermissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{0}
}

// Response message for the GetPermissions RPC.
type GetPermissionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of permissions for the user.
	Permissions []auth.Permission `protobuf:"varint,1,rep,packed,name=permissions,proto3,enum=api.commons.auth.Permission" json:"permissions,omitempty"`
	// List of legacy P3 permissions.
	P3Permissions []commons.Permission `protobuf:"varint,2,rep,packed,name=p3_permissions,json=p3Permissions,proto3,enum=api.commons.Permission" json:"p3_permissions,omitempty"`
	// User entity.
	User *org.User `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// Default operator application for user.
	DefaultApp commons.OperatorApplications `protobuf:"varint,4,opt,name=default_app,json=defaultApp,proto3,enum=api.commons.OperatorApplications" json:"default_app,omitempty"`
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *GetPermissionsResponse) GetPermissions() []auth.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetPermissionsResponse) GetP3Permissions() []commons.Permission {
	if x != nil {
		return x.P3Permissions
	}
	return nil
}

func (x *GetPermissionsResponse) GetUser() *org.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetPermissionsResponse) GetDefaultApp() commons.OperatorApplications {
	if x != nil {
		return x.DefaultApp
	}
	return commons.OperatorApplications(0)
}

// Request message for the GetUserPermissions RPC.
type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{2}
}

// Response message for the GetUserPermissions RPC.
type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of permissions for the user.
	Permissions []auth.Permission `protobuf:"varint,1,rep,packed,name=permissions,proto3,enum=api.commons.auth.Permission" json:"permissions,omitempty"`
	// A list of the labels associated with the user
	Labels []*org.Label `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPermissionsResponse) GetPermissions() []auth.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetUserPermissionsResponse) GetLabels() []*org.Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Request message for the CreatePermissionGroup RPC.
type CreatePermissionGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of permission group
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Permissions to include in new permission group
	Permissions []auth.Permission `protobuf:"varint,3,rep,packed,name=permissions,proto3,enum=api.commons.auth.Permission" json:"permissions,omitempty"`
}

func (x *CreatePermissionGroupRequest) Reset() {
	*x = CreatePermissionGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePermissionGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionGroupRequest) ProtoMessage() {}

func (x *CreatePermissionGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionGroupRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePermissionGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePermissionGroupRequest) GetPermissions() []auth.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Response message for the CreatePermissionGroup RPC.
type CreatePermissionGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The permission group that was just created.
	PermissionGroupId string `protobuf:"bytes,1,opt,name=permission_group_id,json=permissionGroupId,proto3" json:"permission_group_id,omitempty"`
}

func (x *CreatePermissionGroupResponse) Reset() {
	*x = CreatePermissionGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePermissionGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionGroupResponse) ProtoMessage() {}

func (x *CreatePermissionGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionGroupResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePermissionGroupResponse) GetPermissionGroupId() string {
	if x != nil {
		return x.PermissionGroupId
	}
	return ""
}

// Request message for the UpdatePermissionGroup RPC.
type UpdatePermissionGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of the permission group to be updated.
	PermissionGroupId string `protobuf:"bytes,1,opt,name=permission_group_id,json=permissionGroupId,proto3" json:"permission_group_id,omitempty"`
	// Name of permission group
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of permission group
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Permissions to include in new permission group
	Permissions []auth.Permission `protobuf:"varint,4,rep,packed,name=permissions,proto3,enum=api.commons.auth.Permission" json:"permissions,omitempty"`
}

func (x *UpdatePermissionGroupRequest) Reset() {
	*x = UpdatePermissionGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePermissionGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionGroupRequest) ProtoMessage() {}

func (x *UpdatePermissionGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePermissionGroupRequest) GetPermissionGroupId() string {
	if x != nil {
		return x.PermissionGroupId
	}
	return ""
}

func (x *UpdatePermissionGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePermissionGroupRequest) GetPermissions() []auth.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Response message for the UpdatePermissionGroup RPC.
type UpdatePermissionGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Updated permission group.
	PermissionGroup *org.PermissionGroup `protobuf:"bytes,1,opt,name=permission_group,json=permissionGroup,proto3" json:"permission_group,omitempty"`
}

func (x *UpdatePermissionGroupResponse) Reset() {
	*x = UpdatePermissionGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePermissionGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionGroupResponse) ProtoMessage() {}

func (x *UpdatePermissionGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePermissionGroupResponse) GetPermissionGroup() *org.PermissionGroup {
	if x != nil {
		return x.PermissionGroup
	}
	return nil
}

// Request message for the DeletePermissionGroup RPC.
type DeletePermissionGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of the permission group to be deleted.
	PermissionGroupId string `protobuf:"bytes,1,opt,name=permission_group_id,json=permissionGroupId,proto3" json:"permission_group_id,omitempty"`
}

func (x *DeletePermissionGroupRequest) Reset() {
	*x = DeletePermissionGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePermissionGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionGroupRequest) ProtoMessage() {}

func (x *DeletePermissionGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionGroupRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePermissionGroupRequest) GetPermissionGroupId() string {
	if x != nil {
		return x.PermissionGroupId
	}
	return ""
}

// Response message for the DeletePermissionGroup RPC.
type DeletePermissionGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePermissionGroupResponse) Reset() {
	*x = DeletePermissionGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePermissionGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionGroupResponse) ProtoMessage() {}

func (x *DeletePermissionGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionGroupResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{9}
}

// Request message for the GetPermissions RPC.
type ListPermissionGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPermissionGroupsRequest) Reset() {
	*x = ListPermissionGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPermissionGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionGroupsRequest) ProtoMessage() {}

func (x *ListPermissionGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{10}
}

// Response message for the GetPermissions RPC.
type ListPermissionGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Permission groups in caller's organization
	PermissionGroups []*org.PermissionGroup `protobuf:"bytes,1,rep,name=permission_groups,json=permissionGroups,proto3" json:"permission_groups,omitempty"`
}

func (x *ListPermissionGroupsResponse) Reset() {
	*x = ListPermissionGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPermissionGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionGroupsResponse) ProtoMessage() {}

func (x *ListPermissionGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{11}
}

func (x *ListPermissionGroupsResponse) GetPermissionGroups() []*org.PermissionGroup {
	if x != nil {
		return x.PermissionGroups
	}
	return nil
}

// Request message for the GetPermissions RPC.
type ListPermissionGroupsByOrgIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of organization to get permission groups for
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
}

func (x *ListPermissionGroupsByOrgIdRequest) Reset() {
	*x = ListPermissionGroupsByOrgIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPermissionGroupsByOrgIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionGroupsByOrgIdRequest) ProtoMessage() {}

func (x *ListPermissionGroupsByOrgIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionGroupsByOrgIdRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionGroupsByOrgIdRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{12}
}

func (x *ListPermissionGroupsByOrgIdRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// Response message for the GetPermissions RPC.
type ListPermissionGroupsByOrgIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Permission groups in specified organization
	PermissionGroups []*org.PermissionGroup `protobuf:"bytes,1,rep,name=permission_groups,json=permissionGroups,proto3" json:"permission_groups,omitempty"`
}

func (x *ListPermissionGroupsByOrgIdResponse) Reset() {
	*x = ListPermissionGroupsByOrgIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPermissionGroupsByOrgIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionGroupsByOrgIdResponse) ProtoMessage() {}

func (x *ListPermissionGroupsByOrgIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionGroupsByOrgIdResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionGroupsByOrgIdResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{13}
}

func (x *ListPermissionGroupsByOrgIdResponse) GetPermissionGroups() []*org.PermissionGroup {
	if x != nil {
		return x.PermissionGroups
	}
	return nil
}

// Request message for the AssignUsersPermissionGroup RPC.
type AssignUsersPermissionGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The ID of the permission group that is being assigned.
	PermissionGroupId string `protobuf:"bytes,1,opt,name=permission_group_id,json=permissionGroupId,proto3" json:"permission_group_id,omitempty"`
	// Required. The IDs of the users the permission group is being assigned to.
	AssignUserIds []string `protobuf:"bytes,2,rep,name=assign_user_ids,json=assignUserIds,proto3" json:"assign_user_ids,omitempty"`
}

func (x *AssignUsersPermissionGroupRequest) Reset() {
	*x = AssignUsersPermissionGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignUsersPermissionGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUsersPermissionGroupRequest) ProtoMessage() {}

func (x *AssignUsersPermissionGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUsersPermissionGroupRequest.ProtoReflect.Descriptor instead.
func (*AssignUsersPermissionGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{14}
}

func (x *AssignUsersPermissionGroupRequest) GetPermissionGroupId() string {
	if x != nil {
		return x.PermissionGroupId
	}
	return ""
}

func (x *AssignUsersPermissionGroupRequest) GetAssignUserIds() []string {
	if x != nil {
		return x.AssignUserIds
	}
	return nil
}

// Response message for the AssignUsersPermissionGroup RPC.
type AssignUsersPermissionGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignUsersPermissionGroupResponse) Reset() {
	*x = AssignUsersPermissionGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignUsersPermissionGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUsersPermissionGroupResponse) ProtoMessage() {}

func (x *AssignUsersPermissionGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUsersPermissionGroupResponse.ProtoReflect.Descriptor instead.
func (*AssignUsersPermissionGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{15}
}

// Request message for the RevokeUsersPermissionGroup RPC.
type RevokeUsersPermissionGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The ID of the permission group that is being revoked.
	PermissionGroupId string `protobuf:"bytes,1,opt,name=permission_group_id,json=permissionGroupId,proto3" json:"permission_group_id,omitempty"`
	// Required. The IDs of the users the permission group is being revoked from.
	RevokeUserIds []string `protobuf:"bytes,2,rep,name=revoke_user_ids,json=revokeUserIds,proto3" json:"revoke_user_ids,omitempty"`
}

func (x *RevokeUsersPermissionGroupRequest) Reset() {
	*x = RevokeUsersPermissionGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeUsersPermissionGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUsersPermissionGroupRequest) ProtoMessage() {}

func (x *RevokeUsersPermissionGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUsersPermissionGroupRequest.ProtoReflect.Descriptor instead.
func (*RevokeUsersPermissionGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeUsersPermissionGroupRequest) GetPermissionGroupId() string {
	if x != nil {
		return x.PermissionGroupId
	}
	return ""
}

func (x *RevokeUsersPermissionGroupRequest) GetRevokeUserIds() []string {
	if x != nil {
		return x.RevokeUserIds
	}
	return nil
}

// Response message for the RevokeUsersPermissionGroup RPC.
type RevokeUsersPermissionGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RevokeUsersPermissionGroupResponse) Reset() {
	*x = RevokeUsersPermissionGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeUsersPermissionGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUsersPermissionGroupResponse) ProtoMessage() {}

func (x *RevokeUsersPermissionGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUsersPermissionGroupResponse.ProtoReflect.Descriptor instead.
func (*RevokeUsersPermissionGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{17}
}

// Request message for the AssignAccountOwnerPermissionToUser RPC.
type AssignAccountOwnerPermissionToUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User which will be assigned the account owner permissions.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *AssignAccountOwnerPermissionToUserRequest) Reset() {
	*x = AssignAccountOwnerPermissionToUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignAccountOwnerPermissionToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAccountOwnerPermissionToUserRequest) ProtoMessage() {}

func (x *AssignAccountOwnerPermissionToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAccountOwnerPermissionToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignAccountOwnerPermissionToUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{18}
}

func (x *AssignAccountOwnerPermissionToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for the AssignAccountOwnerPermissionToUser RPC.
type AssignAccountOwnerPermissionToUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignAccountOwnerPermissionToUserResponse) Reset() {
	*x = AssignAccountOwnerPermissionToUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignAccountOwnerPermissionToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAccountOwnerPermissionToUserResponse) ProtoMessage() {}

func (x *AssignAccountOwnerPermissionToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAccountOwnerPermissionToUserResponse.ProtoReflect.Descriptor instead.
func (*AssignAccountOwnerPermissionToUserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{19}
}

// Request message for the RevokeAccountOwnerPermissionFromUser RPC.
type RevokeAccountOwnerPermissionFromUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User which will be revoked the account owner permissions.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The organization which the target user belongs to
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
}

func (x *RevokeAccountOwnerPermissionFromUserRequest) Reset() {
	*x = RevokeAccountOwnerPermissionFromUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAccountOwnerPermissionFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccountOwnerPermissionFromUserRequest) ProtoMessage() {}

func (x *RevokeAccountOwnerPermissionFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccountOwnerPermissionFromUserRequest.ProtoReflect.Descriptor instead.
func (*RevokeAccountOwnerPermissionFromUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{20}
}

func (x *RevokeAccountOwnerPermissionFromUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeAccountOwnerPermissionFromUserRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// Response message for the RevokeAccountOwnerPermissionFromUser RPC.
type RevokeAccountOwnerPermissionFromUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RevokeAccountOwnerPermissionFromUserResponse) Reset() {
	*x = RevokeAccountOwnerPermissionFromUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAccountOwnerPermissionFromUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccountOwnerPermissionFromUserResponse) ProtoMessage() {}

func (x *RevokeAccountOwnerPermissionFromUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccountOwnerPermissionFromUserResponse.ProtoReflect.Descriptor instead.
func (*RevokeAccountOwnerPermissionFromUserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{21}
}

// Request message for the InitDefaultPermissionGroups RPC.
type InitDefaultPermissionGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitDefaultPermissionGroupsRequest) Reset() {
	*x = InitDefaultPermissionGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitDefaultPermissionGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDefaultPermissionGroupsRequest) ProtoMessage() {}

func (x *InitDefaultPermissionGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDefaultPermissionGroupsRequest.ProtoReflect.Descriptor instead.
func (*InitDefaultPermissionGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{22}
}

// Response message for the InitDefaultPermissionGroups RPC.
type InitDefaultPermissionGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of default permission groups.
	DefaultPermissionGroups []*org.PermissionGroup `protobuf:"bytes,1,rep,name=default_permission_groups,json=defaultPermissionGroups,proto3" json:"default_permission_groups,omitempty"`
}

func (x *InitDefaultPermissionGroupsResponse) Reset() {
	*x = InitDefaultPermissionGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitDefaultPermissionGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDefaultPermissionGroupsResponse) ProtoMessage() {}

func (x *InitDefaultPermissionGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDefaultPermissionGroupsResponse.ProtoReflect.Descriptor instead.
func (*InitDefaultPermissionGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{23}
}

func (x *InitDefaultPermissionGroupsResponse) GetDefaultPermissionGroups() []*org.PermissionGroup {
	if x != nil {
		return x.DefaultPermissionGroups
	}
	return nil
}

// Request message for the GetAccountOwnerGroup RPC.
type GetAccountOwnerGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of organization to get account owner group for
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
}

func (x *GetAccountOwnerGroupRequest) Reset() {
	*x = GetAccountOwnerGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountOwnerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountOwnerGroupRequest) ProtoMessage() {}

func (x *GetAccountOwnerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountOwnerGroupRequest.ProtoReflect.Descriptor instead.
func (*GetAccountOwnerGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{24}
}

func (x *GetAccountOwnerGroupRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// Response message for the GetAccountOwnerGroup RPC.
type GetAccountOwnerGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Permission groups in specified organization
	PermissionGroup *org.PermissionGroup `protobuf:"bytes,1,opt,name=permission_group,json=permissionGroup,proto3" json:"permission_group,omitempty"`
}

func (x *GetAccountOwnerGroupResponse) Reset() {
	*x = GetAccountOwnerGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountOwnerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountOwnerGroupResponse) ProtoMessage() {}

func (x *GetAccountOwnerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountOwnerGroupResponse.ProtoReflect.Descriptor instead.
func (*GetAccountOwnerGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{25}
}

func (x *GetAccountOwnerGroupResponse) GetPermissionGroup() *org.PermissionGroup {
	if x != nil {
		return x.PermissionGroup
	}
	return nil
}

// Request message for the GetLicenses RPC.
type GetLicensesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Org ID to retrieve the assigned licenses for.
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
}

func (x *GetLicensesRequest) Reset() {
	*x = GetLicensesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLicensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLicensesRequest) ProtoMessage() {}

func (x *GetLicensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLicensesRequest.ProtoReflect.Descriptor instead.
func (*GetLicensesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{26}
}

func (x *GetLicensesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// Response message for the GetLicenses RPC.
type GetLicensesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of licenses organization is authorized for.
	Licenses []*org.License `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
}

func (x *GetLicensesResponse) Reset() {
	*x = GetLicensesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLicensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLicensesResponse) ProtoMessage() {}

func (x *GetLicensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLicensesResponse.ProtoReflect.Descriptor instead.
func (*GetLicensesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{27}
}

func (x *GetLicensesResponse) GetLicenses() []*org.License {
	if x != nil {
		return x.Licenses
	}
	return nil
}

// Request message for the GetOrgLicenses RPC.
type GetOrgLicensesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOrgLicensesRequest) Reset() {
	*x = GetOrgLicensesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrgLicensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgLicensesRequest) ProtoMessage() {}

func (x *GetOrgLicensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgLicensesRequest.ProtoReflect.Descriptor instead.
func (*GetOrgLicensesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{28}
}

// Response message for the GetOrgLicenses RPC.
type GetOrgLicensesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of licenses organization is authorized for.
	Licenses []*org.License `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
}

func (x *GetOrgLicensesResponse) Reset() {
	*x = GetOrgLicensesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrgLicensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgLicensesResponse) ProtoMessage() {}

func (x *GetOrgLicensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgLicensesResponse.ProtoReflect.Descriptor instead.
func (*GetOrgLicensesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{29}
}

func (x *GetOrgLicensesResponse) GetLicenses() []*org.License {
	if x != nil {
		return x.Licenses
	}
	return nil
}

// Request message for the UpdateLicenses RPC.
type UpdateLicensesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Org ID to update the assigned licenses for.
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Permissions to add to license.
	AddedLicenses []auth.Permission `protobuf:"varint,2,rep,packed,name=added_licenses,json=addedLicenses,proto3,enum=api.commons.auth.Permission" json:"added_licenses,omitempty"`
	// Permissions to revoke from license.
	RevokedLicenses []auth.Permission `protobuf:"varint,3,rep,packed,name=revoked_licenses,json=revokedLicenses,proto3,enum=api.commons.auth.Permission" json:"revoked_licenses,omitempty"`
}

func (x *UpdateLicensesRequest) Reset() {
	*x = UpdateLicensesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLicensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLicensesRequest) ProtoMessage() {}

func (x *UpdateLicensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLicensesRequest.ProtoReflect.Descriptor instead.
func (*UpdateLicensesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateLicensesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateLicensesRequest) GetAddedLicenses() []auth.Permission {
	if x != nil {
		return x.AddedLicenses
	}
	return nil
}

func (x *UpdateLicensesRequest) GetRevokedLicenses() []auth.Permission {
	if x != nil {
		return x.RevokedLicenses
	}
	return nil
}

// Response message for the UpdateLicenses RPC.
type UpdateLicensesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLicensesResponse) Reset() {
	*x = UpdateLicensesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLicensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLicensesResponse) ProtoMessage() {}

func (x *UpdateLicensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLicensesResponse.ProtoReflect.Descriptor instead.
func (*UpdateLicensesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{31}
}

// Request message for the RemovePermissionFromAllPermissionGroupsRequest RPC.
type RemovePermissionFromAllPermissionGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Org ID to remove the permission from.
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Permission to remove from all permission groups.
	Permission auth.Permission `protobuf:"varint,2,opt,name=permission,proto3,enum=api.commons.auth.Permission" json:"permission,omitempty"`
}

func (x *RemovePermissionFromAllPermissionGroupsRequest) Reset() {
	*x = RemovePermissionFromAllPermissionGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePermissionFromAllPermissionGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermissionFromAllPermissionGroupsRequest) ProtoMessage() {}

func (x *RemovePermissionFromAllPermissionGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermissionFromAllPermissionGroupsRequest.ProtoReflect.Descriptor instead.
func (*RemovePermissionFromAllPermissionGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{32}
}

func (x *RemovePermissionFromAllPermissionGroupsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RemovePermissionFromAllPermissionGroupsRequest) GetPermission() auth.Permission {
	if x != nil {
		return x.Permission
	}
	return auth.Permission(0)
}

// Response message for the RemovePermissionFromAllPermissionGroupsRequest RPC.
type RemovePermissionFromAllPermissionGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemovePermissionFromAllPermissionGroupsResponse) Reset() {
	*x = RemovePermissionFromAllPermissionGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePermissionFromAllPermissionGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermissionFromAllPermissionGroupsResponse) ProtoMessage() {}

func (x *RemovePermissionFromAllPermissionGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_permissions_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermissionFromAllPermissionGroupsResponse.ProtoReflect.Descriptor instead.
func (*RemovePermissionFromAllPermissionGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_permissions_proto_rawDescGZIP(), []int{33}
}

var File_api_v1alpha1_org_permissions_proto protoreflect.FileDescriptor

var file_api_v1alpha1_org_permissions_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6f,
	0x72, 0x67, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x1a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x73, 0x2f, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x6f, 0x72, 0x67, 0x2f, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x6f, 0x72, 0x67, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x87, 0x02, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x70, 0x33, 0x5f, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x70, 0x33, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x42, 0x0a, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x41, 0x70, 0x70, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x2e, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x22, 0x94, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4f, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x1c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x6c, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4b, 0x0a, 0x10, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0f, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x4e, 0x0a,
	0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x13, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x1f, 0x0a,
	0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d,
	0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6d, 0x0a,
	0x1c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a,
	0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x10, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x3b, 0x0a, 0x22,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x42, 0x79, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x23, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x42, 0x79, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x10, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22,
	0x7b, 0x0a, 0x21, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x24, 0x0a, 0x22,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x7b, 0x0a, 0x21, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x76, 0x6f, 0x6b,
	0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22,
	0x24, 0x0a, 0x22, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x29, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x2a, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x2b, 0x52, 0x65, 0x76,
	0x6f, 0x6b, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x2c, 0x52, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x22, 0x49, 0x6e, 0x69, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x83,
	0x01, 0x0a, 0x23, 0x49, 0x6e, 0x69, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x19, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x17, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x22, 0x34, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x2b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x72, 0x67, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x6c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x73, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x67, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0e, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73,
	0x12, 0x47, 0x0a, 0x10, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x63, 0x65,
	0x6e, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x64, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x3c, 0x0a,
	0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x2f, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46,
	0x72, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4e,
	0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x63, 0x6e, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x6f, 0x72,
	0x67, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x63,
	0x6e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6f, 0x72, 0x67, 0x3b, 0x6f, 0x72, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1alpha1_org_permissions_proto_rawDescOnce sync.Once
	file_api_v1alpha1_org_permissions_proto_rawDescData = file_api_v1alpha1_org_permissions_proto_rawDesc
)

func file_api_v1alpha1_org_permissions_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_org_permissions_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_org_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1alpha1_org_permissions_proto_rawDescData)
	})
	return file_api_v1alpha1_org_permissions_proto_rawDescData
}

var file_api_v1alpha1_org_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_v1alpha1_org_permissions_proto_goTypes = []interface{}{
	(*GetPermissionsRequest)(nil),                           // 0: api.v1alpha1.org.GetPermissionsRequest
	(*GetPermissionsResponse)(nil),                          // 1: api.v1alpha1.org.GetPermissionsResponse
	(*GetUserPermissionsRequest)(nil),                       // 2: api.v1alpha1.org.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil),                      // 3: api.v1alpha1.org.GetUserPermissionsResponse
	(*CreatePermissionGroupRequest)(nil),                    // 4: api.v1alpha1.org.CreatePermissionGroupRequest
	(*CreatePermissionGroupResponse)(nil),                   // 5: api.v1alpha1.org.CreatePermissionGroupResponse
	(*UpdatePermissionGroupRequest)(nil),                    // 6: api.v1alpha1.org.UpdatePermissionGroupRequest
	(*UpdatePermissionGroupResponse)(nil),                   // 7: api.v1alpha1.org.UpdatePermissionGroupResponse
	(*DeletePermissionGroupRequest)(nil),                    // 8: api.v1alpha1.org.DeletePermissionGroupRequest
	(*DeletePermissionGroupResponse)(nil),                   // 9: api.v1alpha1.org.DeletePermissionGroupResponse
	(*ListPermissionGroupsRequest)(nil),                     // 10: api.v1alpha1.org.ListPermissionGroupsRequest
	(*ListPermissionGroupsResponse)(nil),                    // 11: api.v1alpha1.org.ListPermissionGroupsResponse
	(*ListPermissionGroupsByOrgIdRequest)(nil),              // 12: api.v1alpha1.org.ListPermissionGroupsByOrgIdRequest
	(*ListPermissionGroupsByOrgIdResponse)(nil),             // 13: api.v1alpha1.org.ListPermissionGroupsByOrgIdResponse
	(*AssignUsersPermissionGroupRequest)(nil),               // 14: api.v1alpha1.org.AssignUsersPermissionGroupRequest
	(*AssignUsersPermissionGroupResponse)(nil),              // 15: api.v1alpha1.org.AssignUsersPermissionGroupResponse
	(*RevokeUsersPermissionGroupRequest)(nil),               // 16: api.v1alpha1.org.RevokeUsersPermissionGroupRequest
	(*RevokeUsersPermissionGroupResponse)(nil),              // 17: api.v1alpha1.org.RevokeUsersPermissionGroupResponse
	(*AssignAccountOwnerPermissionToUserRequest)(nil),       // 18: api.v1alpha1.org.AssignAccountOwnerPermissionToUserRequest
	(*AssignAccountOwnerPermissionToUserResponse)(nil),      // 19: api.v1alpha1.org.AssignAccountOwnerPermissionToUserResponse
	(*RevokeAccountOwnerPermissionFromUserRequest)(nil),     // 20: api.v1alpha1.org.RevokeAccountOwnerPermissionFromUserRequest
	(*RevokeAccountOwnerPermissionFromUserResponse)(nil),    // 21: api.v1alpha1.org.RevokeAccountOwnerPermissionFromUserResponse
	(*InitDefaultPermissionGroupsRequest)(nil),              // 22: api.v1alpha1.org.InitDefaultPermissionGroupsRequest
	(*InitDefaultPermissionGroupsResponse)(nil),             // 23: api.v1alpha1.org.InitDefaultPermissionGroupsResponse
	(*GetAccountOwnerGroupRequest)(nil),                     // 24: api.v1alpha1.org.GetAccountOwnerGroupRequest
	(*GetAccountOwnerGroupResponse)(nil),                    // 25: api.v1alpha1.org.GetAccountOwnerGroupResponse
	(*GetLicensesRequest)(nil),                              // 26: api.v1alpha1.org.GetLicensesRequest
	(*GetLicensesResponse)(nil),                             // 27: api.v1alpha1.org.GetLicensesResponse
	(*GetOrgLicensesRequest)(nil),                           // 28: api.v1alpha1.org.GetOrgLicensesRequest
	(*GetOrgLicensesResponse)(nil),                          // 29: api.v1alpha1.org.GetOrgLicensesResponse
	(*UpdateLicensesRequest)(nil),                           // 30: api.v1alpha1.org.UpdateLicensesRequest
	(*UpdateLicensesResponse)(nil),                          // 31: api.v1alpha1.org.UpdateLicensesResponse
	(*RemovePermissionFromAllPermissionGroupsRequest)(nil),  // 32: api.v1alpha1.org.RemovePermissionFromAllPermissionGroupsRequest
	(*RemovePermissionFromAllPermissionGroupsResponse)(nil), // 33: api.v1alpha1.org.RemovePermissionFromAllPermissionGroupsResponse
	(auth.Permission)(0),                                    // 34: api.commons.auth.Permission
	(commons.Permission)(0),                                 // 35: api.commons.Permission
	(*org.User)(nil),                                        // 36: api.commons.org.User
	(commons.OperatorApplications)(0),                       // 37: api.commons.OperatorApplications
	(*org.Label)(nil),                                       // 38: api.commons.org.Label
	(*org.PermissionGroup)(nil),                             // 39: api.commons.org.PermissionGroup
	(*org.License)(nil),                                     // 40: api.commons.org.License
}
var file_api_v1alpha1_org_permissions_proto_depIdxs = []int32{
	34, // 0: api.v1alpha1.org.GetPermissionsResponse.permissions:type_name -> api.commons.auth.Permission
	35, // 1: api.v1alpha1.org.GetPermissionsResponse.p3_permissions:type_name -> api.commons.Permission
	36, // 2: api.v1alpha1.org.GetPermissionsResponse.user:type_name -> api.commons.org.User
	37, // 3: api.v1alpha1.org.GetPermissionsResponse.default_app:type_name -> api.commons.OperatorApplications
	34, // 4: api.v1alpha1.org.GetUserPermissionsResponse.permissions:type_name -> api.commons.auth.Permission
	38, // 5: api.v1alpha1.org.GetUserPermissionsResponse.labels:type_name -> api.commons.org.Label
	34, // 6: api.v1alpha1.org.CreatePermissionGroupRequest.permissions:type_name -> api.commons.auth.Permission
	34, // 7: api.v1alpha1.org.UpdatePermissionGroupRequest.permissions:type_name -> api.commons.auth.Permission
	39, // 8: api.v1alpha1.org.UpdatePermissionGroupResponse.permission_group:type_name -> api.commons.org.PermissionGroup
	39, // 9: api.v1alpha1.org.ListPermissionGroupsResponse.permission_groups:type_name -> api.commons.org.PermissionGroup
	39, // 10: api.v1alpha1.org.ListPermissionGroupsByOrgIdResponse.permission_groups:type_name -> api.commons.org.PermissionGroup
	39, // 11: api.v1alpha1.org.InitDefaultPermissionGroupsResponse.default_permission_groups:type_name -> api.commons.org.PermissionGroup
	39, // 12: api.v1alpha1.org.GetAccountOwnerGroupResponse.permission_group:type_name -> api.commons.org.PermissionGroup
	40, // 13: api.v1alpha1.org.GetLicensesResponse.licenses:type_name -> api.commons.org.License
	40, // 14: api.v1alpha1.org.GetOrgLicensesResponse.licenses:type_name -> api.commons.org.License
	34, // 15: api.v1alpha1.org.UpdateLicensesRequest.added_licenses:type_name -> api.commons.auth.Permission
	34, // 16: api.v1alpha1.org.UpdateLicensesRequest.revoked_licenses:type_name -> api.commons.auth.Permission
	34, // 17: api.v1alpha1.org.RemovePermissionFromAllPermissionGroupsRequest.permission:type_name -> api.commons.auth.Permission
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_org_permissions_proto_init() }
func file_api_v1alpha1_org_permissions_proto_init() {
	if File_api_v1alpha1_org_permissions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1alpha1_org_permissions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPermissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPermissionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPermissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPermissionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePermissionGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePermissionGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePermissionGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePermissionGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePermissionGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePermissionGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPermissionGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPermissionGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPermissionGroupsByOrgIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPermissionGroupsByOrgIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignUsersPermissionGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignUsersPermissionGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeUsersPermissionGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeUsersPermissionGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignAccountOwnerPermissionToUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignAccountOwnerPermissionToUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeAccountOwnerPermissionFromUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeAccountOwnerPermissionFromUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitDefaultPermissionGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitDefaultPermissionGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountOwnerGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountOwnerGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLicensesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLicensesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrgLicensesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrgLicensesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLicensesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLicensesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePermissionFromAllPermissionGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_permissions_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePermissionFromAllPermissionGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1alpha1_org_permissions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1alpha1_org_permissions_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_org_permissions_proto_depIdxs,
		MessageInfos:      file_api_v1alpha1_org_permissions_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_org_permissions_proto = out.File
	file_api_v1alpha1_org_permissions_proto_rawDesc = nil
	file_api_v1alpha1_org_permissions_proto_goTypes = nil
	file_api_v1alpha1_org_permissions_proto_depIdxs = nil
}
