// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/v1alpha1/workflows/service.proto

package workflows

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkflowsDefinitionsService_ListFlowDefinitions_FullMethodName      = "/api.v1alpha1.workflows.WorkflowsDefinitionsService/ListFlowDefinitions"
	WorkflowsDefinitionsService_SaveFlowDefinition_FullMethodName       = "/api.v1alpha1.workflows.WorkflowsDefinitionsService/SaveFlowDefinition"
	WorkflowsDefinitionsService_GetFlowDefinition_FullMethodName        = "/api.v1alpha1.workflows.WorkflowsDefinitionsService/GetFlowDefinition"
	WorkflowsDefinitionsService_DeleteFlowDefinitionById_FullMethodName = "/api.v1alpha1.workflows.WorkflowsDefinitionsService/DeleteFlowDefinitionById"
)

// WorkflowsDefinitionsServiceClient is the client API for WorkflowsDefinitionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowsDefinitionsServiceClient interface {
	// ListFlowDefinitions lists flow definitions
	ListFlowDefinitions(ctx context.Context, in *ListFlowDefinitionsRequest, opts ...grpc.CallOption) (*ListFlowDefinitionsResponse, error)
	// SaveFlowDefinition creates or updates a flow definition
	SaveFlowDefinition(ctx context.Context, in *SaveFlowDefinitionRequest, opts ...grpc.CallOption) (*SaveFlowDefinitionResponse, error)
	// GetFlowDefinition gets a flow definition
	GetFlowDefinition(ctx context.Context, in *GetFlowDefinitionRequest, opts ...grpc.CallOption) (*GetFlowDefinitionResponse, error)
	// DeleteFlowDefinition deletes a flow definition
	DeleteFlowDefinitionById(ctx context.Context, in *DeleteFlowDefinitionByIdRequest, opts ...grpc.CallOption) (*DeleteFlowDefinitionByIdResponse, error)
}

type workflowsDefinitionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowsDefinitionsServiceClient(cc grpc.ClientConnInterface) WorkflowsDefinitionsServiceClient {
	return &workflowsDefinitionsServiceClient{cc}
}

func (c *workflowsDefinitionsServiceClient) ListFlowDefinitions(ctx context.Context, in *ListFlowDefinitionsRequest, opts ...grpc.CallOption) (*ListFlowDefinitionsResponse, error) {
	out := new(ListFlowDefinitionsResponse)
	err := c.cc.Invoke(ctx, WorkflowsDefinitionsService_ListFlowDefinitions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsDefinitionsServiceClient) SaveFlowDefinition(ctx context.Context, in *SaveFlowDefinitionRequest, opts ...grpc.CallOption) (*SaveFlowDefinitionResponse, error) {
	out := new(SaveFlowDefinitionResponse)
	err := c.cc.Invoke(ctx, WorkflowsDefinitionsService_SaveFlowDefinition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsDefinitionsServiceClient) GetFlowDefinition(ctx context.Context, in *GetFlowDefinitionRequest, opts ...grpc.CallOption) (*GetFlowDefinitionResponse, error) {
	out := new(GetFlowDefinitionResponse)
	err := c.cc.Invoke(ctx, WorkflowsDefinitionsService_GetFlowDefinition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsDefinitionsServiceClient) DeleteFlowDefinitionById(ctx context.Context, in *DeleteFlowDefinitionByIdRequest, opts ...grpc.CallOption) (*DeleteFlowDefinitionByIdResponse, error) {
	out := new(DeleteFlowDefinitionByIdResponse)
	err := c.cc.Invoke(ctx, WorkflowsDefinitionsService_DeleteFlowDefinitionById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowsDefinitionsServiceServer is the server API for WorkflowsDefinitionsService service.
// All implementations must embed UnimplementedWorkflowsDefinitionsServiceServer
// for forward compatibility
type WorkflowsDefinitionsServiceServer interface {
	// ListFlowDefinitions lists flow definitions
	ListFlowDefinitions(context.Context, *ListFlowDefinitionsRequest) (*ListFlowDefinitionsResponse, error)
	// SaveFlowDefinition creates or updates a flow definition
	SaveFlowDefinition(context.Context, *SaveFlowDefinitionRequest) (*SaveFlowDefinitionResponse, error)
	// GetFlowDefinition gets a flow definition
	GetFlowDefinition(context.Context, *GetFlowDefinitionRequest) (*GetFlowDefinitionResponse, error)
	// DeleteFlowDefinition deletes a flow definition
	DeleteFlowDefinitionById(context.Context, *DeleteFlowDefinitionByIdRequest) (*DeleteFlowDefinitionByIdResponse, error)
	mustEmbedUnimplementedWorkflowsDefinitionsServiceServer()
}

// UnimplementedWorkflowsDefinitionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkflowsDefinitionsServiceServer struct {
}

func (UnimplementedWorkflowsDefinitionsServiceServer) ListFlowDefinitions(context.Context, *ListFlowDefinitionsRequest) (*ListFlowDefinitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlowDefinitions not implemented")
}
func (UnimplementedWorkflowsDefinitionsServiceServer) SaveFlowDefinition(context.Context, *SaveFlowDefinitionRequest) (*SaveFlowDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFlowDefinition not implemented")
}
func (UnimplementedWorkflowsDefinitionsServiceServer) GetFlowDefinition(context.Context, *GetFlowDefinitionRequest) (*GetFlowDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowDefinition not implemented")
}
func (UnimplementedWorkflowsDefinitionsServiceServer) DeleteFlowDefinitionById(context.Context, *DeleteFlowDefinitionByIdRequest) (*DeleteFlowDefinitionByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFlowDefinitionById not implemented")
}
func (UnimplementedWorkflowsDefinitionsServiceServer) mustEmbedUnimplementedWorkflowsDefinitionsServiceServer() {
}

// UnsafeWorkflowsDefinitionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowsDefinitionsServiceServer will
// result in compilation errors.
type UnsafeWorkflowsDefinitionsServiceServer interface {
	mustEmbedUnimplementedWorkflowsDefinitionsServiceServer()
}

func RegisterWorkflowsDefinitionsServiceServer(s grpc.ServiceRegistrar, srv WorkflowsDefinitionsServiceServer) {
	s.RegisterService(&WorkflowsDefinitionsService_ServiceDesc, srv)
}

func _WorkflowsDefinitionsService_ListFlowDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlowDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsDefinitionsServiceServer).ListFlowDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsDefinitionsService_ListFlowDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsDefinitionsServiceServer).ListFlowDefinitions(ctx, req.(*ListFlowDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsDefinitionsService_SaveFlowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFlowDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsDefinitionsServiceServer).SaveFlowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsDefinitionsService_SaveFlowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsDefinitionsServiceServer).SaveFlowDefinition(ctx, req.(*SaveFlowDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsDefinitionsService_GetFlowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsDefinitionsServiceServer).GetFlowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsDefinitionsService_GetFlowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsDefinitionsServiceServer).GetFlowDefinition(ctx, req.(*GetFlowDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsDefinitionsService_DeleteFlowDefinitionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlowDefinitionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsDefinitionsServiceServer).DeleteFlowDefinitionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsDefinitionsService_DeleteFlowDefinitionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsDefinitionsServiceServer).DeleteFlowDefinitionById(ctx, req.(*DeleteFlowDefinitionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowsDefinitionsService_ServiceDesc is the grpc.ServiceDesc for WorkflowsDefinitionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowsDefinitionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1alpha1.workflows.WorkflowsDefinitionsService",
	HandlerType: (*WorkflowsDefinitionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlowDefinitions",
			Handler:    _WorkflowsDefinitionsService_ListFlowDefinitions_Handler,
		},
		{
			MethodName: "SaveFlowDefinition",
			Handler:    _WorkflowsDefinitionsService_SaveFlowDefinition_Handler,
		},
		{
			MethodName: "GetFlowDefinition",
			Handler:    _WorkflowsDefinitionsService_GetFlowDefinition_Handler,
		},
		{
			MethodName: "DeleteFlowDefinitionById",
			Handler:    _WorkflowsDefinitionsService_DeleteFlowDefinitionById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1alpha1/workflows/service.proto",
}

const (
	WorkflowsStateService_GetFlowState_FullMethodName  = "/api.v1alpha1.workflows.WorkflowsStateService/GetFlowState"
	WorkflowsStateService_SaveFlowState_FullMethodName = "/api.v1alpha1.workflows.WorkflowsStateService/SaveFlowState"
)

// WorkflowsStateServiceClient is the client API for WorkflowsStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowsStateServiceClient interface {
	// GetFlowState lists flow state
	GetFlowState(ctx context.Context, in *GetFlowStateRequest, opts ...grpc.CallOption) (*GetFlowStateResponse, error)
	// SaveFlowState saves flow state
	SaveFlowState(ctx context.Context, in *SaveFlowStateRequest, opts ...grpc.CallOption) (*SaveFlowStateResponse, error)
}

type workflowsStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowsStateServiceClient(cc grpc.ClientConnInterface) WorkflowsStateServiceClient {
	return &workflowsStateServiceClient{cc}
}

func (c *workflowsStateServiceClient) GetFlowState(ctx context.Context, in *GetFlowStateRequest, opts ...grpc.CallOption) (*GetFlowStateResponse, error) {
	out := new(GetFlowStateResponse)
	err := c.cc.Invoke(ctx, WorkflowsStateService_GetFlowState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsStateServiceClient) SaveFlowState(ctx context.Context, in *SaveFlowStateRequest, opts ...grpc.CallOption) (*SaveFlowStateResponse, error) {
	out := new(SaveFlowStateResponse)
	err := c.cc.Invoke(ctx, WorkflowsStateService_SaveFlowState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowsStateServiceServer is the server API for WorkflowsStateService service.
// All implementations must embed UnimplementedWorkflowsStateServiceServer
// for forward compatibility
type WorkflowsStateServiceServer interface {
	// GetFlowState lists flow state
	GetFlowState(context.Context, *GetFlowStateRequest) (*GetFlowStateResponse, error)
	// SaveFlowState saves flow state
	SaveFlowState(context.Context, *SaveFlowStateRequest) (*SaveFlowStateResponse, error)
	mustEmbedUnimplementedWorkflowsStateServiceServer()
}

// UnimplementedWorkflowsStateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkflowsStateServiceServer struct {
}

func (UnimplementedWorkflowsStateServiceServer) GetFlowState(context.Context, *GetFlowStateRequest) (*GetFlowStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowState not implemented")
}
func (UnimplementedWorkflowsStateServiceServer) SaveFlowState(context.Context, *SaveFlowStateRequest) (*SaveFlowStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFlowState not implemented")
}
func (UnimplementedWorkflowsStateServiceServer) mustEmbedUnimplementedWorkflowsStateServiceServer() {}

// UnsafeWorkflowsStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowsStateServiceServer will
// result in compilation errors.
type UnsafeWorkflowsStateServiceServer interface {
	mustEmbedUnimplementedWorkflowsStateServiceServer()
}

func RegisterWorkflowsStateServiceServer(s grpc.ServiceRegistrar, srv WorkflowsStateServiceServer) {
	s.RegisterService(&WorkflowsStateService_ServiceDesc, srv)
}

func _WorkflowsStateService_GetFlowState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsStateServiceServer).GetFlowState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsStateService_GetFlowState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsStateServiceServer).GetFlowState(ctx, req.(*GetFlowStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsStateService_SaveFlowState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFlowStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsStateServiceServer).SaveFlowState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsStateService_SaveFlowState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsStateServiceServer).SaveFlowState(ctx, req.(*SaveFlowStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowsStateService_ServiceDesc is the grpc.ServiceDesc for WorkflowsStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowsStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1alpha1.workflows.WorkflowsStateService",
	HandlerType: (*WorkflowsStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlowState",
			Handler:    _WorkflowsStateService_GetFlowState_Handler,
		},
		{
			MethodName: "SaveFlowState",
			Handler:    _WorkflowsStateService_SaveFlowState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1alpha1/workflows/service.proto",
}
