// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/v1alpha1/org/skills/entities.proto

package skills

import (
	org "github.com/tcncloud/api-go/api/commons/org"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for the CreateSkillGroup rpc.
type CreateSkillGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill group object to create. It is expected to have the org id on it
	SkillGroup *org.SkillGroup `protobuf:"bytes,1,opt,name=skill_group,json=skillGroup,proto3" json:"skill_group,omitempty"`
}

func (x *CreateSkillGroupRequest) Reset() {
	*x = CreateSkillGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSkillGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillGroupRequest) ProtoMessage() {}

func (x *CreateSkillGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSkillGroupRequest) GetSkillGroup() *org.SkillGroup {
	if x != nil {
		return x.SkillGroup
	}
	return nil
}

// Response message for the CreateSkillGroup rpc.
type CreateSkillGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the created skill group.
	SkillGroupId string `protobuf:"bytes,1,opt,name=skill_group_id,json=skillGroupId,proto3" json:"skill_group_id,omitempty"`
}

func (x *CreateSkillGroupResponse) Reset() {
	*x = CreateSkillGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSkillGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillGroupResponse) ProtoMessage() {}

func (x *CreateSkillGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillGroupResponse) GetSkillGroupId() string {
	if x != nil {
		return x.SkillGroupId
	}
	return ""
}

// Request message for the ListSkillGroups rpc.
type ListSkillGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Mask to filter fields on skill group entities in response.
	FieldMask []string `protobuf:"bytes,1,rep,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
}

func (x *ListSkillGroupsRequest) Reset() {
	*x = ListSkillGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillGroupsRequest) ProtoMessage() {}

func (x *ListSkillGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{2}
}

func (x *ListSkillGroupsRequest) GetFieldMask() []string {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response message for the ListSkillGroups rpc.
type ListSkillGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill groups in the organization.
	SkillGroups []*org.SkillGroup `protobuf:"bytes,1,rep,name=skill_groups,json=skillGroups,proto3" json:"skill_groups,omitempty"`
}

func (x *ListSkillGroupsResponse) Reset() {
	*x = ListSkillGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillGroupsResponse) ProtoMessage() {}

func (x *ListSkillGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{3}
}

func (x *ListSkillGroupsResponse) GetSkillGroups() []*org.SkillGroup {
	if x != nil {
		return x.SkillGroups
	}
	return nil
}

// Request message for the UpdateSkillGroup rpc.
type UpdateSkillGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The desired updated skill group object. It is expected to have the skill group id and org id on it
	SkillGroup *org.SkillGroup `protobuf:"bytes,1,opt,name=skill_group,json=skillGroup,proto3" json:"skill_group,omitempty"`
	// Mask to filter fields on skill group to update.
	FieldMask []string `protobuf:"bytes,2,rep,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
}

func (x *UpdateSkillGroupRequest) Reset() {
	*x = UpdateSkillGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSkillGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillGroupRequest) ProtoMessage() {}

func (x *UpdateSkillGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSkillGroupRequest) GetSkillGroup() *org.SkillGroup {
	if x != nil {
		return x.SkillGroup
	}
	return nil
}

func (x *UpdateSkillGroupRequest) GetFieldMask() []string {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response message for the UpdateSkillGroup rpc.
type UpdateSkillGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSkillGroupResponse) Reset() {
	*x = UpdateSkillGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSkillGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillGroupResponse) ProtoMessage() {}

func (x *UpdateSkillGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateSkillGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{5}
}

// Request message for the GetSkillGroup rpc.
type GetSkillGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill group id of the skill group
	SkillGroupId string `protobuf:"bytes,1,opt,name=skill_group_id,json=skillGroupId,proto3" json:"skill_group_id,omitempty"`
	// Mask to filter fields on skill group entity in response.
	FieldMask []string `protobuf:"bytes,2,rep,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
}

func (x *GetSkillGroupRequest) Reset() {
	*x = GetSkillGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSkillGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillGroupRequest) ProtoMessage() {}

func (x *GetSkillGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillGroupRequest.ProtoReflect.Descriptor instead.
func (*GetSkillGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{6}
}

func (x *GetSkillGroupRequest) GetSkillGroupId() string {
	if x != nil {
		return x.SkillGroupId
	}
	return ""
}

func (x *GetSkillGroupRequest) GetFieldMask() []string {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response message for the GetSkillGroup rpc.
type GetSkillGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The requested skill group.
	SkillGroup *org.SkillGroup `protobuf:"bytes,1,opt,name=skill_group,json=skillGroup,proto3" json:"skill_group,omitempty"`
}

func (x *GetSkillGroupResponse) Reset() {
	*x = GetSkillGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSkillGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillGroupResponse) ProtoMessage() {}

func (x *GetSkillGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillGroupResponse.ProtoReflect.Descriptor instead.
func (*GetSkillGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{7}
}

func (x *GetSkillGroupResponse) GetSkillGroup() *org.SkillGroup {
	if x != nil {
		return x.SkillGroup
	}
	return nil
}

// Request message for the DeleteSkillGroup rpc.
type DeleteSkillGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill group id of the skill group to delete.
	SkillGroupId string `protobuf:"bytes,1,opt,name=skill_group_id,json=skillGroupId,proto3" json:"skill_group_id,omitempty"`
}

func (x *DeleteSkillGroupRequest) Reset() {
	*x = DeleteSkillGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSkillGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillGroupRequest) ProtoMessage() {}

func (x *DeleteSkillGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSkillGroupRequest) GetSkillGroupId() string {
	if x != nil {
		return x.SkillGroupId
	}
	return ""
}

// Response message for the DeleteSkillGroup rpc.
type DeleteSkillGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSkillGroupResponse) Reset() {
	*x = DeleteSkillGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSkillGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillGroupResponse) ProtoMessage() {}

func (x *DeleteSkillGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkillGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{9}
}

// Request message for the RemoveSkillFromAllGroups rpc.
type RemoveSkillFromAllGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill sid of the skill to remove.
	SkillSid int64 `protobuf:"varint,1,opt,name=skill_sid,json=skillSid,proto3" json:"skill_sid,omitempty"`
}

func (x *RemoveSkillFromAllGroupsRequest) Reset() {
	*x = RemoveSkillFromAllGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSkillFromAllGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillFromAllGroupsRequest) ProtoMessage() {}

func (x *RemoveSkillFromAllGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillFromAllGroupsRequest.ProtoReflect.Descriptor instead.
func (*RemoveSkillFromAllGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveSkillFromAllGroupsRequest) GetSkillSid() int64 {
	if x != nil {
		return x.SkillSid
	}
	return 0
}

// Response message for the RemoveSkillFromAllGroups rpc.
type RemoveSkillFromAllGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveSkillFromAllGroupsResponse) Reset() {
	*x = RemoveSkillFromAllGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSkillFromAllGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillFromAllGroupsResponse) ProtoMessage() {}

func (x *RemoveSkillFromAllGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillFromAllGroupsResponse.ProtoReflect.Descriptor instead.
func (*RemoveSkillFromAllGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{11}
}

// Request message for the AssignSkillGroups rpc.
type AssignSkillGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ids of the skill groups to be assigned.
	SkillGroupIds []string `protobuf:"bytes,1,rep,name=skill_group_ids,json=skillGroupIds,proto3" json:"skill_group_ids,omitempty"`
	// The user id of the user.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *AssignSkillGroupsRequest) Reset() {
	*x = AssignSkillGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignSkillGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSkillGroupsRequest) ProtoMessage() {}

func (x *AssignSkillGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSkillGroupsRequest.ProtoReflect.Descriptor instead.
func (*AssignSkillGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{12}
}

func (x *AssignSkillGroupsRequest) GetSkillGroupIds() []string {
	if x != nil {
		return x.SkillGroupIds
	}
	return nil
}

func (x *AssignSkillGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for the AssignSkillGroups rpc.
type AssignSkillGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignSkillGroupsResponse) Reset() {
	*x = AssignSkillGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignSkillGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSkillGroupsResponse) ProtoMessage() {}

func (x *AssignSkillGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSkillGroupsResponse.ProtoReflect.Descriptor instead.
func (*AssignSkillGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{13}
}

// Request message for the RevokeSkillGroups rpc.
type RevokeSkillGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ids of the skill groups to be revoked.
	SkillGroupIds []string `protobuf:"bytes,1,rep,name=skill_group_ids,json=skillGroupIds,proto3" json:"skill_group_ids,omitempty"`
	// The user id of the user.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RevokeSkillGroupsRequest) Reset() {
	*x = RevokeSkillGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeSkillGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSkillGroupsRequest) ProtoMessage() {}

func (x *RevokeSkillGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSkillGroupsRequest.ProtoReflect.Descriptor instead.
func (*RevokeSkillGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeSkillGroupsRequest) GetSkillGroupIds() []string {
	if x != nil {
		return x.SkillGroupIds
	}
	return nil
}

func (x *RevokeSkillGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for the RevokeSkillGroups rpc.
type RevokeSkillGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RevokeSkillGroupsResponse) Reset() {
	*x = RevokeSkillGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeSkillGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSkillGroupsResponse) ProtoMessage() {}

func (x *RevokeSkillGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSkillGroupsResponse.ProtoReflect.Descriptor instead.
func (*RevokeSkillGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{15}
}

// Request message for the GetUserSkillGroups rpc.
type GetUserSkillGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The user id of the user.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserSkillGroupsRequest) Reset() {
	*x = GetUserSkillGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSkillGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSkillGroupsRequest) ProtoMessage() {}

func (x *GetUserSkillGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSkillGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSkillGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserSkillGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for the GetUserSkillGroups rpc.
type GetUserSkillGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill group ids assigned to the user.
	SkillGroupIds []string `protobuf:"bytes,1,rep,name=skill_group_ids,json=skillGroupIds,proto3" json:"skill_group_ids,omitempty"`
}

func (x *GetUserSkillGroupsResponse) Reset() {
	*x = GetUserSkillGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSkillGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSkillGroupsResponse) ProtoMessage() {}

func (x *GetUserSkillGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSkillGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSkillGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserSkillGroupsResponse) GetSkillGroupIds() []string {
	if x != nil {
		return x.SkillGroupIds
	}
	return nil
}

// Request message for the GetUserSkills rpc.
type GetUserSkillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The user id of the user.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserSkillsRequest) Reset() {
	*x = GetUserSkillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSkillsRequest) ProtoMessage() {}

func (x *GetUserSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSkillsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSkillsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserSkillsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for the GetUserSkills rpc.
type GetUserSkillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill sets a user has.
	SkillSets []*org.SkillSet `protobuf:"bytes,1,rep,name=skill_sets,json=skillSets,proto3" json:"skill_sets,omitempty"`
}

func (x *GetUserSkillsResponse) Reset() {
	*x = GetUserSkillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSkillsResponse) ProtoMessage() {}

func (x *GetUserSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSkillsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSkillsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserSkillsResponse) GetSkillSets() []*org.SkillSet {
	if x != nil {
		return x.SkillSets
	}
	return nil
}

// Request message for the GetSkillGroupMembers rpc.
type GetSkillGroupMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The skill group id of the skill group.
	SkillGroupId string `protobuf:"bytes,1,opt,name=skill_group_id,json=skillGroupId,proto3" json:"skill_group_id,omitempty"`
}

func (x *GetSkillGroupMembersRequest) Reset() {
	*x = GetSkillGroupMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSkillGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillGroupMembersRequest) ProtoMessage() {}

func (x *GetSkillGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*GetSkillGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{20}
}

func (x *GetSkillGroupMembersRequest) GetSkillGroupId() string {
	if x != nil {
		return x.SkillGroupId
	}
	return ""
}

// Response message for the GetSkillGroupMembers rpc.
type GetSkillGroupMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The users ids which belong to the skill group.
	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *GetSkillGroupMembersResponse) Reset() {
	*x = GetSkillGroupMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSkillGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillGroupMembersResponse) ProtoMessage() {}

func (x *GetSkillGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*GetSkillGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{21}
}

func (x *GetSkillGroupMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Request message for the ListSkillGroupsMembers rpc.
type ListSkillGroupsMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSkillGroupsMembersRequest) Reset() {
	*x = ListSkillGroupsMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillGroupsMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillGroupsMembersRequest) ProtoMessage() {}

func (x *ListSkillGroupsMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillGroupsMembersRequest.ProtoReflect.Descriptor instead.
func (*ListSkillGroupsMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{22}
}

// Response message for the ListSkillGroupsMembers rpc.
type ListSkillGroupsMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillGroupMembers []*SkillGroupMembers `protobuf:"bytes,1,rep,name=skill_group_members,json=skillGroupMembers,proto3" json:"skill_group_members,omitempty"`
}

func (x *ListSkillGroupsMembersResponse) Reset() {
	*x = ListSkillGroupsMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillGroupsMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillGroupsMembersResponse) ProtoMessage() {}

func (x *ListSkillGroupsMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillGroupsMembersResponse.ProtoReflect.Descriptor instead.
func (*ListSkillGroupsMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{23}
}

func (x *ListSkillGroupsMembersResponse) GetSkillGroupMembers() []*SkillGroupMembers {
	if x != nil {
		return x.SkillGroupMembers
	}
	return nil
}

// Submessage for ListSkillGroupsMembersResponse.
type SkillGroupMembers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillGroupId string   `protobuf:"bytes,1,opt,name=skill_group_id,json=skillGroupId,proto3" json:"skill_group_id,omitempty"`
	UserIds      []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *SkillGroupMembers) Reset() {
	*x = SkillGroupMembers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillGroupMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillGroupMembers) ProtoMessage() {}

func (x *SkillGroupMembers) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillGroupMembers.ProtoReflect.Descriptor instead.
func (*SkillGroupMembers) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{24}
}

func (x *SkillGroupMembers) GetSkillGroupId() string {
	if x != nil {
		return x.SkillGroupId
	}
	return ""
}

func (x *SkillGroupMembers) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Request message for the UpdateUsersOnSkillGroup rpc.
type UpdateUsersOnSkillGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the skill group the users are being assigned to.
	SkillGroupId string `protobuf:"bytes,1,opt,name=skill_group_id,json=skillGroupId,proto3" json:"skill_group_id,omitempty"`
	// IDs of the users being assigned to the skill group.
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *UpdateUsersOnSkillGroupRequest) Reset() {
	*x = UpdateUsersOnSkillGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsersOnSkillGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersOnSkillGroupRequest) ProtoMessage() {}

func (x *UpdateUsersOnSkillGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersOnSkillGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsersOnSkillGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateUsersOnSkillGroupRequest) GetSkillGroupId() string {
	if x != nil {
		return x.SkillGroupId
	}
	return ""
}

func (x *UpdateUsersOnSkillGroupRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Response message for the UpdateUsersOnSkillGroup rpc.
type UpdateUsersOnSkillGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUsersOnSkillGroupResponse) Reset() {
	*x = UpdateUsersOnSkillGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsersOnSkillGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersOnSkillGroupResponse) ProtoMessage() {}

func (x *UpdateUsersOnSkillGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersOnSkillGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateUsersOnSkillGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{26}
}

// Request message for the ListSkillsForCurrentAgent RPC.
type ListSkillsForCurrentAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSkillsForCurrentAgentRequest) Reset() {
	*x = ListSkillsForCurrentAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillsForCurrentAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsForCurrentAgentRequest) ProtoMessage() {}

func (x *ListSkillsForCurrentAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsForCurrentAgentRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsForCurrentAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{27}
}

// Response message for the ListSkillsForCurrentAgent RPC.
type ListSkillsForCurrentAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The returned list of skills belonging to the current agent.
	Skills []*ListSkillsForCurrentAgentResponse_AgentSkill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
}

func (x *ListSkillsForCurrentAgentResponse) Reset() {
	*x = ListSkillsForCurrentAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillsForCurrentAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsForCurrentAgentResponse) ProtoMessage() {}

func (x *ListSkillsForCurrentAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsForCurrentAgentResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsForCurrentAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{28}
}

func (x *ListSkillsForCurrentAgentResponse) GetSkills() []*ListSkillsForCurrentAgentResponse_AgentSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// Response message for the GetAgentSkills RPC.
type GetAgentSkillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAgentSkillsRequest) Reset() {
	*x = GetAgentSkillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentSkillsRequest) ProtoMessage() {}

func (x *GetAgentSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentSkillsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentSkillsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{29}
}

// Response message for the GetAgentSkills RPC.
type GetAgentSkillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// skills found for the given parameters, will be value pairs (name, level).
	Skills map[string]int64 `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetAgentSkillsResponse) Reset() {
	*x = GetAgentSkillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentSkillsResponse) ProtoMessage() {}

func (x *GetAgentSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentSkillsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentSkillsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{30}
}

func (x *GetAgentSkillsResponse) GetSkills() map[string]int64 {
	if x != nil {
		return x.Skills
	}
	return nil
}

type ListSkillsForCurrentAgentResponse_AgentSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentSkillSid int64  `protobuf:"varint,1,opt,name=agent_skill_sid,json=agentSkillSid,proto3" json:"agent_skill_sid,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ListSkillsForCurrentAgentResponse_AgentSkill) Reset() {
	*x = ListSkillsForCurrentAgentResponse_AgentSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillsForCurrentAgentResponse_AgentSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsForCurrentAgentResponse_AgentSkill) ProtoMessage() {}

func (x *ListSkillsForCurrentAgentResponse_AgentSkill) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_org_skills_entities_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsForCurrentAgentResponse_AgentSkill.ProtoReflect.Descriptor instead.
func (*ListSkillsForCurrentAgentResponse_AgentSkill) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP(), []int{28, 0}
}

func (x *ListSkillsForCurrentAgentResponse_AgentSkill) GetAgentSkillSid() int64 {
	if x != nil {
		return x.AgentSkillSid
	}
	return 0
}

func (x *ListSkillsForCurrentAgentResponse_AgentSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSkillsForCurrentAgentResponse_AgentSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_v1alpha1_org_skills_entities_proto protoreflect.FileDescriptor

var file_api_v1alpha1_org_skills_entities_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6f,
	0x72, 0x67, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x1a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x6f,
	0x72, 0x67, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3c, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x40, 0x0a,
	0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x59, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x22, 0x76, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c,
	0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x1a, 0x0a, 0x18, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4d, 0x61, 0x73, 0x6b, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x3f, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x1f, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x18,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x18, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x34, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x22, 0x2f, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f,
	0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x73,
	0x22, 0x43, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x22, 0x1f, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x7c, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x13, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x11, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22,
	0x54, 0x0a, 0x11, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x61, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x4f, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x21, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4f, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xee, 0x01, 0x0a, 0x21, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x46, 0x6f,
	0x72, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x1a, 0x6a, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x5f, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0xe0, 0x01, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x42, 0x0d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x63, 0x6e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6f,
	0x72, 0x67, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0xa2, 0x02, 0x04, 0x41, 0x56, 0x4f, 0x53,
	0xaa, 0x02, 0x17, 0x41, 0x70, 0x69, 0x2e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x4f, 0x72, 0x67, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0xca, 0x02, 0x17, 0x41, 0x70, 0x69,
	0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x4f, 0x72, 0x67, 0x5c, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0xe2, 0x02, 0x23, 0x41, 0x70, 0x69, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x5c, 0x4f, 0x72, 0x67, 0x5c, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1a, 0x41, 0x70, 0x69,
	0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3a, 0x3a, 0x4f, 0x72, 0x67, 0x3a,
	0x3a, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1alpha1_org_skills_entities_proto_rawDescOnce sync.Once
	file_api_v1alpha1_org_skills_entities_proto_rawDescData = file_api_v1alpha1_org_skills_entities_proto_rawDesc
)

func file_api_v1alpha1_org_skills_entities_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_org_skills_entities_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_org_skills_entities_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1alpha1_org_skills_entities_proto_rawDescData)
	})
	return file_api_v1alpha1_org_skills_entities_proto_rawDescData
}

var file_api_v1alpha1_org_skills_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_v1alpha1_org_skills_entities_proto_goTypes = []interface{}{
	(*CreateSkillGroupRequest)(nil),                      // 0: api.v1alpha1.org.skills.CreateSkillGroupRequest
	(*CreateSkillGroupResponse)(nil),                     // 1: api.v1alpha1.org.skills.CreateSkillGroupResponse
	(*ListSkillGroupsRequest)(nil),                       // 2: api.v1alpha1.org.skills.ListSkillGroupsRequest
	(*ListSkillGroupsResponse)(nil),                      // 3: api.v1alpha1.org.skills.ListSkillGroupsResponse
	(*UpdateSkillGroupRequest)(nil),                      // 4: api.v1alpha1.org.skills.UpdateSkillGroupRequest
	(*UpdateSkillGroupResponse)(nil),                     // 5: api.v1alpha1.org.skills.UpdateSkillGroupResponse
	(*GetSkillGroupRequest)(nil),                         // 6: api.v1alpha1.org.skills.GetSkillGroupRequest
	(*GetSkillGroupResponse)(nil),                        // 7: api.v1alpha1.org.skills.GetSkillGroupResponse
	(*DeleteSkillGroupRequest)(nil),                      // 8: api.v1alpha1.org.skills.DeleteSkillGroupRequest
	(*DeleteSkillGroupResponse)(nil),                     // 9: api.v1alpha1.org.skills.DeleteSkillGroupResponse
	(*RemoveSkillFromAllGroupsRequest)(nil),              // 10: api.v1alpha1.org.skills.RemoveSkillFromAllGroupsRequest
	(*RemoveSkillFromAllGroupsResponse)(nil),             // 11: api.v1alpha1.org.skills.RemoveSkillFromAllGroupsResponse
	(*AssignSkillGroupsRequest)(nil),                     // 12: api.v1alpha1.org.skills.AssignSkillGroupsRequest
	(*AssignSkillGroupsResponse)(nil),                    // 13: api.v1alpha1.org.skills.AssignSkillGroupsResponse
	(*RevokeSkillGroupsRequest)(nil),                     // 14: api.v1alpha1.org.skills.RevokeSkillGroupsRequest
	(*RevokeSkillGroupsResponse)(nil),                    // 15: api.v1alpha1.org.skills.RevokeSkillGroupsResponse
	(*GetUserSkillGroupsRequest)(nil),                    // 16: api.v1alpha1.org.skills.GetUserSkillGroupsRequest
	(*GetUserSkillGroupsResponse)(nil),                   // 17: api.v1alpha1.org.skills.GetUserSkillGroupsResponse
	(*GetUserSkillsRequest)(nil),                         // 18: api.v1alpha1.org.skills.GetUserSkillsRequest
	(*GetUserSkillsResponse)(nil),                        // 19: api.v1alpha1.org.skills.GetUserSkillsResponse
	(*GetSkillGroupMembersRequest)(nil),                  // 20: api.v1alpha1.org.skills.GetSkillGroupMembersRequest
	(*GetSkillGroupMembersResponse)(nil),                 // 21: api.v1alpha1.org.skills.GetSkillGroupMembersResponse
	(*ListSkillGroupsMembersRequest)(nil),                // 22: api.v1alpha1.org.skills.ListSkillGroupsMembersRequest
	(*ListSkillGroupsMembersResponse)(nil),               // 23: api.v1alpha1.org.skills.ListSkillGroupsMembersResponse
	(*SkillGroupMembers)(nil),                            // 24: api.v1alpha1.org.skills.SkillGroupMembers
	(*UpdateUsersOnSkillGroupRequest)(nil),               // 25: api.v1alpha1.org.skills.UpdateUsersOnSkillGroupRequest
	(*UpdateUsersOnSkillGroupResponse)(nil),              // 26: api.v1alpha1.org.skills.UpdateUsersOnSkillGroupResponse
	(*ListSkillsForCurrentAgentRequest)(nil),             // 27: api.v1alpha1.org.skills.ListSkillsForCurrentAgentRequest
	(*ListSkillsForCurrentAgentResponse)(nil),            // 28: api.v1alpha1.org.skills.ListSkillsForCurrentAgentResponse
	(*GetAgentSkillsRequest)(nil),                        // 29: api.v1alpha1.org.skills.GetAgentSkillsRequest
	(*GetAgentSkillsResponse)(nil),                       // 30: api.v1alpha1.org.skills.GetAgentSkillsResponse
	(*ListSkillsForCurrentAgentResponse_AgentSkill)(nil), // 31: api.v1alpha1.org.skills.ListSkillsForCurrentAgentResponse.AgentSkill
	nil,                    // 32: api.v1alpha1.org.skills.GetAgentSkillsResponse.SkillsEntry
	(*org.SkillGroup)(nil), // 33: api.commons.org.SkillGroup
	(*org.SkillSet)(nil),   // 34: api.commons.org.SkillSet
}
var file_api_v1alpha1_org_skills_entities_proto_depIdxs = []int32{
	33, // 0: api.v1alpha1.org.skills.CreateSkillGroupRequest.skill_group:type_name -> api.commons.org.SkillGroup
	33, // 1: api.v1alpha1.org.skills.ListSkillGroupsResponse.skill_groups:type_name -> api.commons.org.SkillGroup
	33, // 2: api.v1alpha1.org.skills.UpdateSkillGroupRequest.skill_group:type_name -> api.commons.org.SkillGroup
	33, // 3: api.v1alpha1.org.skills.GetSkillGroupResponse.skill_group:type_name -> api.commons.org.SkillGroup
	34, // 4: api.v1alpha1.org.skills.GetUserSkillsResponse.skill_sets:type_name -> api.commons.org.SkillSet
	24, // 5: api.v1alpha1.org.skills.ListSkillGroupsMembersResponse.skill_group_members:type_name -> api.v1alpha1.org.skills.SkillGroupMembers
	31, // 6: api.v1alpha1.org.skills.ListSkillsForCurrentAgentResponse.skills:type_name -> api.v1alpha1.org.skills.ListSkillsForCurrentAgentResponse.AgentSkill
	32, // 7: api.v1alpha1.org.skills.GetAgentSkillsResponse.skills:type_name -> api.v1alpha1.org.skills.GetAgentSkillsResponse.SkillsEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_org_skills_entities_proto_init() }
func file_api_v1alpha1_org_skills_entities_proto_init() {
	if File_api_v1alpha1_org_skills_entities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSkillGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSkillGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSkillGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSkillGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSkillGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSkillGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSkillGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSkillGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSkillFromAllGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSkillFromAllGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignSkillGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignSkillGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeSkillGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeSkillGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSkillGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSkillGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSkillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSkillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSkillGroupMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSkillGroupMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillGroupsMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillGroupsMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillGroupMembers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsersOnSkillGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsersOnSkillGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillsForCurrentAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillsForCurrentAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentSkillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentSkillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_org_skills_entities_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillsForCurrentAgentResponse_AgentSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1alpha1_org_skills_entities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1alpha1_org_skills_entities_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_org_skills_entities_proto_depIdxs,
		MessageInfos:      file_api_v1alpha1_org_skills_entities_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_org_skills_entities_proto = out.File
	file_api_v1alpha1_org_skills_entities_proto_rawDesc = nil
	file_api_v1alpha1_org_skills_entities_proto_goTypes = nil
	file_api_v1alpha1_org_skills_entities_proto_depIdxs = nil
}
