// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1alpha1/agenttraining/learning_opportunity.proto

package agenttraining

import (
	commons "github.com/tcncloud/api-go/api/commons"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateLearningOpportunityRequest represents a request to create a new learning opportunity.
type CreateLearningOpportunityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity *commons.LearningOpportunity `protobuf:"bytes,1,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
}

func (x *CreateLearningOpportunityRequest) Reset() {
	*x = CreateLearningOpportunityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLearningOpportunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLearningOpportunityRequest) ProtoMessage() {}

func (x *CreateLearningOpportunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLearningOpportunityRequest.ProtoReflect.Descriptor instead.
func (*CreateLearningOpportunityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLearningOpportunityRequest) GetLearningOpportunity() *commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunity
	}
	return nil
}

// CreateLearningOpportunityResponse represents the created learning opportunity.
type CreateLearningOpportunityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity *commons.LearningOpportunity `protobuf:"bytes,1,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
}

func (x *CreateLearningOpportunityResponse) Reset() {
	*x = CreateLearningOpportunityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLearningOpportunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLearningOpportunityResponse) ProtoMessage() {}

func (x *CreateLearningOpportunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLearningOpportunityResponse.ProtoReflect.Descriptor instead.
func (*CreateLearningOpportunityResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLearningOpportunityResponse) GetLearningOpportunity() *commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunity
	}
	return nil
}

// ListLearningOpportunitiesRequest represents a request to list learning opportunities.
type ListLearningOpportunitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallIdentifiers []*commons.CallIdentifier `protobuf:"bytes,2,rep,name=call_identifiers,json=callIdentifiers,proto3" json:"call_identifiers,omitempty"`      // Optional - 'any of' if provided.
	TranscriptSids  []int64                   `protobuf:"varint,3,rep,packed,name=transcript_sids,json=transcriptSids,proto3" json:"transcript_sids,omitempty"` // Optional - 'any of' if provided.
	AgentUserIds    []string                  `protobuf:"bytes,4,rep,name=agent_user_ids,json=agentUserIds,proto3" json:"agent_user_ids,omitempty"`             // Optional - 'any of' if provided.
	CreatedAt       *commons.TimeFilter       `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                        // Optional.
}

func (x *ListLearningOpportunitiesRequest) Reset() {
	*x = ListLearningOpportunitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLearningOpportunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearningOpportunitiesRequest) ProtoMessage() {}

func (x *ListLearningOpportunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearningOpportunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListLearningOpportunitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{2}
}

func (x *ListLearningOpportunitiesRequest) GetCallIdentifiers() []*commons.CallIdentifier {
	if x != nil {
		return x.CallIdentifiers
	}
	return nil
}

func (x *ListLearningOpportunitiesRequest) GetTranscriptSids() []int64 {
	if x != nil {
		return x.TranscriptSids
	}
	return nil
}

func (x *ListLearningOpportunitiesRequest) GetAgentUserIds() []string {
	if x != nil {
		return x.AgentUserIds
	}
	return nil
}

func (x *ListLearningOpportunitiesRequest) GetCreatedAt() *commons.TimeFilter {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListLearningOpportunitiesResponse represents the listed learning opportunities.
type ListLearningOpportunitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunities []*commons.LearningOpportunity `protobuf:"bytes,1,rep,name=learning_opportunities,json=learningOpportunities,proto3" json:"learning_opportunities,omitempty"`
}

func (x *ListLearningOpportunitiesResponse) Reset() {
	*x = ListLearningOpportunitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLearningOpportunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearningOpportunitiesResponse) ProtoMessage() {}

func (x *ListLearningOpportunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearningOpportunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListLearningOpportunitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{3}
}

func (x *ListLearningOpportunitiesResponse) GetLearningOpportunities() []*commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunities
	}
	return nil
}

// ListAgentLearningOpportunitiesRequest represents a request to list learning opportunities by agent.
type ListAgentLearningOpportunitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallIdentifiers []*commons.CallIdentifier `protobuf:"bytes,2,rep,name=call_identifiers,json=callIdentifiers,proto3" json:"call_identifiers,omitempty"`      // Optional - 'any of' if provided.
	TranscriptSids  []int64                   `protobuf:"varint,3,rep,packed,name=transcript_sids,json=transcriptSids,proto3" json:"transcript_sids,omitempty"` // Optional - 'any of' if provided.
	CreatedAt       *commons.TimeFilter       `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                        // Optional.
}

func (x *ListAgentLearningOpportunitiesRequest) Reset() {
	*x = ListAgentLearningOpportunitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentLearningOpportunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentLearningOpportunitiesRequest) ProtoMessage() {}

func (x *ListAgentLearningOpportunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentLearningOpportunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListAgentLearningOpportunitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentLearningOpportunitiesRequest) GetCallIdentifiers() []*commons.CallIdentifier {
	if x != nil {
		return x.CallIdentifiers
	}
	return nil
}

func (x *ListAgentLearningOpportunitiesRequest) GetTranscriptSids() []int64 {
	if x != nil {
		return x.TranscriptSids
	}
	return nil
}

func (x *ListAgentLearningOpportunitiesRequest) GetCreatedAt() *commons.TimeFilter {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListAgentLearningOpportunitiesResponse represents the listed learning opportunities.
type ListAgentLearningOpportunitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunities []*commons.LearningOpportunity `protobuf:"bytes,1,rep,name=learning_opportunities,json=learningOpportunities,proto3" json:"learning_opportunities,omitempty"`
}

func (x *ListAgentLearningOpportunitiesResponse) Reset() {
	*x = ListAgentLearningOpportunitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentLearningOpportunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentLearningOpportunitiesResponse) ProtoMessage() {}

func (x *ListAgentLearningOpportunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentLearningOpportunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListAgentLearningOpportunitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentLearningOpportunitiesResponse) GetLearningOpportunities() []*commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunities
	}
	return nil
}

// UpdateLearningOpportunityRequest represents a request to update a learning opportunity.
type UpdateLearningOpportunityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity *commons.LearningOpportunity `protobuf:"bytes,2,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
	UpdateMask          *fieldmaskpb.FieldMask       `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
}

func (x *UpdateLearningOpportunityRequest) Reset() {
	*x = UpdateLearningOpportunityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLearningOpportunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLearningOpportunityRequest) ProtoMessage() {}

func (x *UpdateLearningOpportunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLearningOpportunityRequest.ProtoReflect.Descriptor instead.
func (*UpdateLearningOpportunityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLearningOpportunityRequest) GetLearningOpportunity() *commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunity
	}
	return nil
}

func (x *UpdateLearningOpportunityRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateLearningOpportunityResponse represents the updated learning opportunity.
type UpdateLearningOpportunityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity *commons.LearningOpportunity `protobuf:"bytes,1,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
}

func (x *UpdateLearningOpportunityResponse) Reset() {
	*x = UpdateLearningOpportunityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLearningOpportunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLearningOpportunityResponse) ProtoMessage() {}

func (x *UpdateLearningOpportunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLearningOpportunityResponse.ProtoReflect.Descriptor instead.
func (*UpdateLearningOpportunityResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLearningOpportunityResponse) GetLearningOpportunity() *commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunity
	}
	return nil
}

// DeleteLearningOpportunityRequest represents a request to delete a learning opportunity.
type DeleteLearningOpportunityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunityId int64 `protobuf:"varint,3,opt,name=learning_opportunity_id,json=learningOpportunityId,proto3" json:"learning_opportunity_id,omitempty"`
}

func (x *DeleteLearningOpportunityRequest) Reset() {
	*x = DeleteLearningOpportunityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLearningOpportunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLearningOpportunityRequest) ProtoMessage() {}

func (x *DeleteLearningOpportunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLearningOpportunityRequest.ProtoReflect.Descriptor instead.
func (*DeleteLearningOpportunityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLearningOpportunityRequest) GetLearningOpportunityId() int64 {
	if x != nil {
		return x.LearningOpportunityId
	}
	return 0
}

// DeleteLearningOpportunityResponse represents the deleted learning opportunity.
type DeleteLearningOpportunityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity *commons.LearningOpportunity `protobuf:"bytes,1,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
}

func (x *DeleteLearningOpportunityResponse) Reset() {
	*x = DeleteLearningOpportunityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLearningOpportunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLearningOpportunityResponse) ProtoMessage() {}

func (x *DeleteLearningOpportunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLearningOpportunityResponse.ProtoReflect.Descriptor instead.
func (*DeleteLearningOpportunityResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLearningOpportunityResponse) GetLearningOpportunity() *commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunity
	}
	return nil
}

// GetLearningOpportunityRequest represents a request to get a learning opportunity.
type GetLearningOpportunityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity int64 `protobuf:"varint,2,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
}

func (x *GetLearningOpportunityRequest) Reset() {
	*x = GetLearningOpportunityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLearningOpportunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearningOpportunityRequest) ProtoMessage() {}

func (x *GetLearningOpportunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearningOpportunityRequest.ProtoReflect.Descriptor instead.
func (*GetLearningOpportunityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{10}
}

func (x *GetLearningOpportunityRequest) GetLearningOpportunity() int64 {
	if x != nil {
		return x.LearningOpportunity
	}
	return 0
}

// GetLearningOpportunityResponse represents the gotten learning opportunity.
type GetLearningOpportunityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningOpportunity *commons.LearningOpportunity `protobuf:"bytes,1,opt,name=learning_opportunity,json=learningOpportunity,proto3" json:"learning_opportunity,omitempty"`
}

func (x *GetLearningOpportunityResponse) Reset() {
	*x = GetLearningOpportunityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLearningOpportunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearningOpportunityResponse) ProtoMessage() {}

func (x *GetLearningOpportunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearningOpportunityResponse.ProtoReflect.Descriptor instead.
func (*GetLearningOpportunityResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP(), []int{11}
}

func (x *GetLearningOpportunityResponse) GetLearningOpportunity() *commons.LearningOpportunity {
	if x != nil {
		return x.LearningOpportunity
	}
	return nil
}

var File_api_v1alpha1_agenttraining_learning_opportunity_proto protoreflect.FileDescriptor

var file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDesc = []byte{
	0x0a, 0x35, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x1a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x14, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x22, 0x78,
	0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e,
	0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x22, 0xf1, 0x01, 0x0a, 0x20, 0x4c, 0x69, 0x73,
	0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75,
	0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a,
	0x10, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x5f, 0x73, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x53, 0x69, 0x64, 0x73, 0x12, 0x24,
	0x0a, 0x0e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x7c, 0x0a, 0x21,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x16, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e,
	0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x52, 0x15, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xd0, 0x01, 0x0a, 0x25, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x10, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0f, 0x63, 0x61, 0x6c,
	0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x73, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x53, 0x69, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x81, 0x01,
	0x0a, 0x26, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x16, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x15, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x22, 0xb4, 0x01, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x78, 0x0a, 0x21, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a,
	0x14, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x13, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x22, 0x5a, 0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x17, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x78,
	0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e,
	0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x22, 0x52, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x22, 0x75, 0x0a, 0x1e,
	0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53,
	0x0a, 0x14, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x13,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x42, 0xfb, 0x01, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x18, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x63, 0x6e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0xa2, 0x02, 0x03, 0x41, 0x56, 0x41, 0xaa,
	0x02, 0x1a, 0x41, 0x70, 0x69, 0x2e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0xca, 0x02, 0x1a, 0x41,
	0x70, 0x69, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0xe2, 0x02, 0x26, 0x41, 0x70, 0x69, 0x5c,
	0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x1c, 0x41, 0x70, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x3a, 0x3a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescOnce sync.Once
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescData = file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDesc
)

func file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescData)
	})
	return file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDescData
}

var file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1alpha1_agenttraining_learning_opportunity_proto_goTypes = []interface{}{
	(*CreateLearningOpportunityRequest)(nil),       // 0: api.v1alpha1.agenttraining.CreateLearningOpportunityRequest
	(*CreateLearningOpportunityResponse)(nil),      // 1: api.v1alpha1.agenttraining.CreateLearningOpportunityResponse
	(*ListLearningOpportunitiesRequest)(nil),       // 2: api.v1alpha1.agenttraining.ListLearningOpportunitiesRequest
	(*ListLearningOpportunitiesResponse)(nil),      // 3: api.v1alpha1.agenttraining.ListLearningOpportunitiesResponse
	(*ListAgentLearningOpportunitiesRequest)(nil),  // 4: api.v1alpha1.agenttraining.ListAgentLearningOpportunitiesRequest
	(*ListAgentLearningOpportunitiesResponse)(nil), // 5: api.v1alpha1.agenttraining.ListAgentLearningOpportunitiesResponse
	(*UpdateLearningOpportunityRequest)(nil),       // 6: api.v1alpha1.agenttraining.UpdateLearningOpportunityRequest
	(*UpdateLearningOpportunityResponse)(nil),      // 7: api.v1alpha1.agenttraining.UpdateLearningOpportunityResponse
	(*DeleteLearningOpportunityRequest)(nil),       // 8: api.v1alpha1.agenttraining.DeleteLearningOpportunityRequest
	(*DeleteLearningOpportunityResponse)(nil),      // 9: api.v1alpha1.agenttraining.DeleteLearningOpportunityResponse
	(*GetLearningOpportunityRequest)(nil),          // 10: api.v1alpha1.agenttraining.GetLearningOpportunityRequest
	(*GetLearningOpportunityResponse)(nil),         // 11: api.v1alpha1.agenttraining.GetLearningOpportunityResponse
	(*commons.LearningOpportunity)(nil),            // 12: api.commons.LearningOpportunity
	(*commons.CallIdentifier)(nil),                 // 13: api.commons.CallIdentifier
	(*commons.TimeFilter)(nil),                     // 14: api.commons.TimeFilter
	(*fieldmaskpb.FieldMask)(nil),                  // 15: google.protobuf.FieldMask
}
var file_api_v1alpha1_agenttraining_learning_opportunity_proto_depIdxs = []int32{
	12, // 0: api.v1alpha1.agenttraining.CreateLearningOpportunityRequest.learning_opportunity:type_name -> api.commons.LearningOpportunity
	12, // 1: api.v1alpha1.agenttraining.CreateLearningOpportunityResponse.learning_opportunity:type_name -> api.commons.LearningOpportunity
	13, // 2: api.v1alpha1.agenttraining.ListLearningOpportunitiesRequest.call_identifiers:type_name -> api.commons.CallIdentifier
	14, // 3: api.v1alpha1.agenttraining.ListLearningOpportunitiesRequest.created_at:type_name -> api.commons.TimeFilter
	12, // 4: api.v1alpha1.agenttraining.ListLearningOpportunitiesResponse.learning_opportunities:type_name -> api.commons.LearningOpportunity
	13, // 5: api.v1alpha1.agenttraining.ListAgentLearningOpportunitiesRequest.call_identifiers:type_name -> api.commons.CallIdentifier
	14, // 6: api.v1alpha1.agenttraining.ListAgentLearningOpportunitiesRequest.created_at:type_name -> api.commons.TimeFilter
	12, // 7: api.v1alpha1.agenttraining.ListAgentLearningOpportunitiesResponse.learning_opportunities:type_name -> api.commons.LearningOpportunity
	12, // 8: api.v1alpha1.agenttraining.UpdateLearningOpportunityRequest.learning_opportunity:type_name -> api.commons.LearningOpportunity
	15, // 9: api.v1alpha1.agenttraining.UpdateLearningOpportunityRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 10: api.v1alpha1.agenttraining.UpdateLearningOpportunityResponse.learning_opportunity:type_name -> api.commons.LearningOpportunity
	12, // 11: api.v1alpha1.agenttraining.DeleteLearningOpportunityResponse.learning_opportunity:type_name -> api.commons.LearningOpportunity
	12, // 12: api.v1alpha1.agenttraining.GetLearningOpportunityResponse.learning_opportunity:type_name -> api.commons.LearningOpportunity
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_agenttraining_learning_opportunity_proto_init() }
func file_api_v1alpha1_agenttraining_learning_opportunity_proto_init() {
	if File_api_v1alpha1_agenttraining_learning_opportunity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLearningOpportunityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLearningOpportunityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLearningOpportunitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLearningOpportunitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentLearningOpportunitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentLearningOpportunitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLearningOpportunityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLearningOpportunityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLearningOpportunityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLearningOpportunityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLearningOpportunityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLearningOpportunityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1alpha1_agenttraining_learning_opportunity_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_agenttraining_learning_opportunity_proto_depIdxs,
		MessageInfos:      file_api_v1alpha1_agenttraining_learning_opportunity_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_agenttraining_learning_opportunity_proto = out.File
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_rawDesc = nil
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_goTypes = nil
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_depIdxs = nil
}
