// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1alpha1/agenttraining/support_service.proto

package agenttraining

import (
	_ "github.com/tcncloud/api-go/annotations"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1alpha1_agenttraining_support_service_proto protoreflect.FileDescriptor

const file_api_v1alpha1_agenttraining_support_service_proto_rawDesc = "" +
	"\n" +
	"0api/v1alpha1/agenttraining/support_service.proto\x12\x1aapi.v1alpha1.agenttraining\x1a\x17annotations/authz.proto\x1a5api/v1alpha1/agenttraining/learning_opportunity.proto\x1a\x1cgoogle/api/annotations.proto2\xcd\x04\n" +
	"\x1bAgentTrainingSupportService\x12\x95\x02\n" +
	" ListLearningOpportunitiesByOrgId\x12C.api.v1alpha1.agenttraining.ListLearningOpportunitiesByOrgIdRequest\x1a=.api.v1alpha1.agenttraining.ListLearningOpportunitiesResponse\"m\xba\xb8\x91\x02\x05\n" +
	"\x03\b\xc8\x01\x82\xd3\xe4\x93\x02]:\x01*\"X/api/v1alpha1/agenttraining/agenttrainingsupportservice/listlearningopportunitiesbyorgid\x12\x95\x02\n" +
	" DeleteLearningOpportunityByOrgId\x12C.api.v1alpha1.agenttraining.DeleteLearningOpportunityByOrgIdRequest\x1a=.api.v1alpha1.agenttraining.DeleteLearningOpportunityResponse\"m\xba\xb8\x91\x02\x05\n" +
	"\x03\b\xc8\x01\x82\xd3\xe4\x93\x02]:\x01*\"X/api/v1alpha1/agenttraining/agenttrainingsupportservice/deletelearningopportunitybyorgidB\xf6\x01\n" +
	"\x1ecom.api.v1alpha1.agenttrainingB\x13SupportServiceProtoP\x01Z5github.com/tcncloud/api-go/api/v1alpha1/agenttraining\xa2\x02\x03AVA\xaa\x02\x1aApi.V1alpha1.Agenttraining\xca\x02\x1aApi\\V1alpha1\\Agenttraining\xe2\x02&Api\\V1alpha1\\Agenttraining\\GPBMetadata\xea\x02\x1cApi::V1alpha1::Agenttrainingb\x06proto3"

var file_api_v1alpha1_agenttraining_support_service_proto_goTypes = []any{
	(*ListLearningOpportunitiesByOrgIdRequest)(nil), // 0: api.v1alpha1.agenttraining.ListLearningOpportunitiesByOrgIdRequest
	(*DeleteLearningOpportunityByOrgIdRequest)(nil), // 1: api.v1alpha1.agenttraining.DeleteLearningOpportunityByOrgIdRequest
	(*ListLearningOpportunitiesResponse)(nil),       // 2: api.v1alpha1.agenttraining.ListLearningOpportunitiesResponse
	(*DeleteLearningOpportunityResponse)(nil),       // 3: api.v1alpha1.agenttraining.DeleteLearningOpportunityResponse
}
var file_api_v1alpha1_agenttraining_support_service_proto_depIdxs = []int32{
	0, // 0: api.v1alpha1.agenttraining.AgentTrainingSupportService.ListLearningOpportunitiesByOrgId:input_type -> api.v1alpha1.agenttraining.ListLearningOpportunitiesByOrgIdRequest
	1, // 1: api.v1alpha1.agenttraining.AgentTrainingSupportService.DeleteLearningOpportunityByOrgId:input_type -> api.v1alpha1.agenttraining.DeleteLearningOpportunityByOrgIdRequest
	2, // 2: api.v1alpha1.agenttraining.AgentTrainingSupportService.ListLearningOpportunitiesByOrgId:output_type -> api.v1alpha1.agenttraining.ListLearningOpportunitiesResponse
	3, // 3: api.v1alpha1.agenttraining.AgentTrainingSupportService.DeleteLearningOpportunityByOrgId:output_type -> api.v1alpha1.agenttraining.DeleteLearningOpportunityResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_agenttraining_support_service_proto_init() }
func file_api_v1alpha1_agenttraining_support_service_proto_init() {
	if File_api_v1alpha1_agenttraining_support_service_proto != nil {
		return
	}
	file_api_v1alpha1_agenttraining_learning_opportunity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1alpha1_agenttraining_support_service_proto_rawDesc), len(file_api_v1alpha1_agenttraining_support_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_agenttraining_support_service_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_agenttraining_support_service_proto_depIdxs,
	}.Build()
	File_api_v1alpha1_agenttraining_support_service_proto = out.File
	file_api_v1alpha1_agenttraining_support_service_proto_goTypes = nil
	file_api_v1alpha1_agenttraining_support_service_proto_depIdxs = nil
}
