// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/commons/logging.proto

package commons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_OFF    Level = 0
	Level_FATAL  Level = 1
	Level_PANIC  Level = 2
	Level_DPANIC Level = 3
	Level_ERROR  Level = 4
	Level_WARN   Level = 5
	Level_INFO   Level = 6
	Level_DEBUG  Level = 7
	Level_TRACE  Level = 8
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "OFF",
		1: "FATAL",
		2: "PANIC",
		3: "DPANIC",
		4: "ERROR",
		5: "WARN",
		6: "INFO",
		7: "DEBUG",
		8: "TRACE",
	}
	Level_value = map[string]int32{
		"OFF":    0,
		"FATAL":  1,
		"PANIC":  2,
		"DPANIC": 3,
		"ERROR":  4,
		"WARN":   5,
		"INFO":   6,
		"DEBUG":  7,
		"TRACE":  8,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_commons_logging_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_api_commons_logging_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_api_commons_logging_proto_rawDescGZIP(), []int{0}
}

var File_api_commons_logging_proto protoreflect.FileDescriptor

const file_api_commons_logging_proto_rawDesc = "" +
	"\n" +
	"\x19api/commons/logging.proto\x12\vapi.commons*g\n" +
	"\x05Level\x12\a\n" +
	"\x03OFF\x10\x00\x12\t\n" +
	"\x05FATAL\x10\x01\x12\t\n" +
	"\x05PANIC\x10\x02\x12\n" +
	"\n" +
	"\x06DPANIC\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\b\n" +
	"\x04WARN\x10\x05\x12\b\n" +
	"\x04INFO\x10\x06\x12\t\n" +
	"\x05DEBUG\x10\a\x12\t\n" +
	"\x05TRACE\x10\bB\x94\x01\n" +
	"\x0fcom.api.commonsB\fLoggingProtoP\x01Z&github.com/tcncloud/api-go/api/commons\xa2\x02\x03ACX\xaa\x02\vApi.Commons\xca\x02\vApi\\Commons\xe2\x02\x17Api\\Commons\\GPBMetadata\xea\x02\fApi::Commonsb\x06proto3"

var (
	file_api_commons_logging_proto_rawDescOnce sync.Once
	file_api_commons_logging_proto_rawDescData []byte
)

func file_api_commons_logging_proto_rawDescGZIP() []byte {
	file_api_commons_logging_proto_rawDescOnce.Do(func() {
		file_api_commons_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_commons_logging_proto_rawDesc), len(file_api_commons_logging_proto_rawDesc)))
	})
	return file_api_commons_logging_proto_rawDescData
}

var file_api_commons_logging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_commons_logging_proto_goTypes = []any{
	(Level)(0), // 0: api.commons.Level
}
var file_api_commons_logging_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_commons_logging_proto_init() }
func file_api_commons_logging_proto_init() {
	if File_api_commons_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_commons_logging_proto_rawDesc), len(file_api_commons_logging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_commons_logging_proto_goTypes,
		DependencyIndexes: file_api_commons_logging_proto_depIdxs,
		EnumInfos:         file_api_commons_logging_proto_enumTypes,
	}.Build()
	File_api_commons_logging_proto = out.File
	file_api_commons_logging_proto_goTypes = nil
	file_api_commons_logging_proto_depIdxs = nil
}
