// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1alpha1/insights/service.proto

package insights

import (
	_ "github.com/tcncloud/api-go/annotations"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1alpha1_insights_service_proto protoreflect.FileDescriptor

const file_api_v1alpha1_insights_service_proto_rawDesc = "" +
	"\n" +
	"#api/v1alpha1/insights/service.proto\x12\x15api.v1alpha1.insights\x1a\x17annotations/authz.proto\x1a#api/v1alpha1/insights/insight.proto\x1a\x1cgoogle/api/annotations.proto2\x97!\n" +
	"\bInsights\x12\xb3\x01\n" +
	"\rCreateInsight\x12+.api.v1alpha1.insights.CreateInsightRequest\x1a,.api.v1alpha1.insights.CreateInsightResponse\"G\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1alpha1/insights/insights/createinsight\x12\xb4\x01\n" +
	"\fListInsights\x12*.api.v1alpha1.insights.ListInsightsRequest\x1a+.api.v1alpha1.insights.ListInsightsResponse\"K\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xd9\x04\n" +
	"\x03\b\xda\x04\x82\xd3\xe4\x93\x021:\x01*\",/api/v1alpha1/insights/insights/listinsights\x12\xc8\x01\n" +
	"\x12ListInsightsStream\x12*.api.v1alpha1.insights.ListInsightsRequest\x1a1.api.v1alpha1.insights.ListInsightsStreamResponse\"Q\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xd9\x04\n" +
	"\x03\b\xda\x04\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1alpha1/insights/insights/listinsightsstream0\x01\x12\xb9\x01\n" +
	"\x0fListOrgInsights\x12-.api.v1alpha1.insights.ListOrgInsightsRequest\x1a..api.v1alpha1.insights.ListOrgInsightsResponse\"G\xba\xb8\x91\x02\b\n" +
	"\x06\b\xfa\x01\b\xd9\x04\x82\xd3\xe4\x93\x024:\x01*\"//api/v1alpha1/insights/insights/listorginsights\x12\xb3\x01\n" +
	"\rUpdateInsight\x12+.api.v1alpha1.insights.UpdateInsightRequest\x1a,.api.v1alpha1.insights.UpdateInsightResponse\"G\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1alpha1/insights/insights/updateinsight\x12\xb3\x01\n" +
	"\rDeleteInsight\x12+.api.v1alpha1.insights.DeleteInsightRequest\x1a,.api.v1alpha1.insights.DeleteInsightResponse\"G\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1alpha1/insights/insights/deleteinsight\x12\xac\x01\n" +
	"\n" +
	"GetInsight\x12(.api.v1alpha1.insights.GetInsightRequest\x1a).api.v1alpha1.insights.GetInsightResponse\"I\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xd9\x04\n" +
	"\x03\b\xda\x04\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1alpha1/insights/insights/getinsight\x12\xbf\x01\n" +
	"\x14CreateCommonsInsight\x12+.api.v1alpha1.insights.CreateInsightRequest\x1a,.api.v1alpha1.insights.CreateInsightResponse\"L\xba\xb8\x91\x02\b\n" +
	"\x06\b\xfa\x01\b\xde\x04\x82\xd3\xe4\x93\x029:\x01*\"4/api/v1alpha1/insights/insights/createcommonsinsight\x12\xbf\x01\n" +
	"\x14UpdateCommonsInsight\x12+.api.v1alpha1.insights.UpdateInsightRequest\x1a,.api.v1alpha1.insights.UpdateInsightResponse\"L\xba\xb8\x91\x02\b\n" +
	"\x06\b\xfa\x01\b\xde\x04\x82\xd3\xe4\x93\x029:\x01*\"4/api/v1alpha1/insights/insights/updatecommonsinsight\x12\xbf\x01\n" +
	"\x14DeleteCommonsInsight\x12+.api.v1alpha1.insights.DeleteInsightRequest\x1a,.api.v1alpha1.insights.DeleteInsightResponse\"L\xba\xb8\x91\x02\b\n" +
	"\x06\b\xfa\x01\b\xde\x04\x82\xd3\xe4\x93\x029:\x01*\"4/api/v1alpha1/insights/insights/deletecommonsinsight\x12\xaf\x01\n" +
	"\fGetVfsSchema\x12*.api.v1alpha1.insights.GetVfsSchemaRequest\x1a+.api.v1alpha1.insights.GetVfsSchemaResponse\"F\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x021:\x01*\",/api/v1alpha1/insights/insights/getvfsschema\x12\xa3\x01\n" +
	"\tListVfses\x12'.api.v1alpha1.insights.ListVfsesRequest\x1a(.api.v1alpha1.insights.ListVfsesResponse\"C\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1alpha1/insights/insights/listvfses\x12\xbc\x01\n" +
	"\x0eListVfsSchemas\x12,.api.v1alpha1.insights.ListVfsSchemasRequest\x1a-.api.v1alpha1.insights.ListVfsSchemasResponse\"M\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\n" +
	"\x03\b\xd9\x04\x82\xd3\xe4\x93\x023:\x01*\"./api/v1alpha1/insights/insights/listvfsschemas\x12\xb5\x01\n" +
	"\x0ePublishInsight\x12,.api.v1alpha1.insights.PublishInsightRequest\x1a-.api.v1alpha1.insights.PublishInsightResponse\"F\xba\xb8\x91\x02\b\n" +
	"\x06\b\xfa\x01\b\xde\x04\x82\xd3\xe4\x93\x023:\x01*\"./api/v1alpha1/insights/insights/publishinsight\x12\xe3\x01\n" +
	"\x19CreateOutputConfiguration\x127.api.v1alpha1.insights.CreateOutputConfigurationRequest\x1a8.api.v1alpha1.insights.CreateOutputConfigurationResponse\"S\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x02>:\x01*\"9/api/v1alpha1/insights/insights/createoutputconfiguration\x12\xe4\x01\n" +
	"\x18ListOutputConfigurations\x126.api.v1alpha1.insights.ListOutputConfigurationsRequest\x1a7.api.v1alpha1.insights.ListOutputConfigurationsResponse\"W\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xd9\x04\n" +
	"\x03\b\xda\x04\x82\xd3\xe4\x93\x02=:\x01*\"8/api/v1alpha1/insights/insights/listoutputconfigurations\x12\xe3\x01\n" +
	"\x19UpdateOutputConfiguration\x127.api.v1alpha1.insights.UpdateOutputConfigurationRequest\x1a8.api.v1alpha1.insights.UpdateOutputConfigurationResponse\"S\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x02>:\x01*\"9/api/v1alpha1/insights/insights/updateoutputconfiguration\x12\xe3\x01\n" +
	"\x19DeleteOutputConfiguration\x127.api.v1alpha1.insights.DeleteOutputConfigurationRequest\x1a8.api.v1alpha1.insights.DeleteOutputConfigurationResponse\"S\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x02>:\x01*\"9/api/v1alpha1/insights/insights/deleteoutputconfiguration\x12\xdc\x01\n" +
	"\x16GetOutputConfiguration\x124.api.v1alpha1.insights.GetOutputConfigurationRequest\x1a5.api.v1alpha1.insights.GetOutputConfigurationResponse\"U\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xd9\x04\n" +
	"\x03\b\xda\x04\x82\xd3\xe4\x93\x02;:\x01*\"6/api/v1alpha1/insights/insights/getoutputconfiguration\x12\xf3\x01\n" +
	"\x1dSetDefaultOutputConfiguration\x12;.api.v1alpha1.insights.SetDefaultOutputConfigurationRequest\x1a<.api.v1alpha1.insights.SetDefaultOutputConfigurationResponse\"W\xba\xb8\x91\x02\n" +
	"\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xde\x04\x82\xd3\xe4\x93\x02B:\x01*\"=/api/v1alpha1/insights/insights/setdefaultoutputconfiguration\x12\xf8\x01\n" +
	"\x1dGetDefaultOutputConfiguration\x12;.api.v1alpha1.insights.GetDefaultOutputConfigurationRequest\x1a<.api.v1alpha1.insights.GetDefaultOutputConfigurationResponse\"\\\xba\xb8\x91\x02\x0f\n" +
	"\x03\b\xfa\x01\n" +
	"\x03\b\xd9\x04\n" +
	"\x03\b\xda\x04\x82\xd3\xe4\x93\x02B:\x01*\"=/api/v1alpha1/insights/insights/getdefaultoutputconfigurationB\xd1\x01\n" +
	"\x19com.api.v1alpha1.insightsB\fServiceProtoP\x01Z0github.com/tcncloud/api-go/api/v1alpha1/insights\xa2\x02\x03AVI\xaa\x02\x15Api.V1alpha1.Insights\xca\x02\x15Api\\V1alpha1\\Insights\xe2\x02!Api\\V1alpha1\\Insights\\GPBMetadata\xea\x02\x17Api::V1alpha1::Insightsb\x06proto3"

var file_api_v1alpha1_insights_service_proto_goTypes = []any{
	(*CreateInsightRequest)(nil),                  // 0: api.v1alpha1.insights.CreateInsightRequest
	(*ListInsightsRequest)(nil),                   // 1: api.v1alpha1.insights.ListInsightsRequest
	(*ListOrgInsightsRequest)(nil),                // 2: api.v1alpha1.insights.ListOrgInsightsRequest
	(*UpdateInsightRequest)(nil),                  // 3: api.v1alpha1.insights.UpdateInsightRequest
	(*DeleteInsightRequest)(nil),                  // 4: api.v1alpha1.insights.DeleteInsightRequest
	(*GetInsightRequest)(nil),                     // 5: api.v1alpha1.insights.GetInsightRequest
	(*GetVfsSchemaRequest)(nil),                   // 6: api.v1alpha1.insights.GetVfsSchemaRequest
	(*ListVfsesRequest)(nil),                      // 7: api.v1alpha1.insights.ListVfsesRequest
	(*ListVfsSchemasRequest)(nil),                 // 8: api.v1alpha1.insights.ListVfsSchemasRequest
	(*PublishInsightRequest)(nil),                 // 9: api.v1alpha1.insights.PublishInsightRequest
	(*CreateOutputConfigurationRequest)(nil),      // 10: api.v1alpha1.insights.CreateOutputConfigurationRequest
	(*ListOutputConfigurationsRequest)(nil),       // 11: api.v1alpha1.insights.ListOutputConfigurationsRequest
	(*UpdateOutputConfigurationRequest)(nil),      // 12: api.v1alpha1.insights.UpdateOutputConfigurationRequest
	(*DeleteOutputConfigurationRequest)(nil),      // 13: api.v1alpha1.insights.DeleteOutputConfigurationRequest
	(*GetOutputConfigurationRequest)(nil),         // 14: api.v1alpha1.insights.GetOutputConfigurationRequest
	(*SetDefaultOutputConfigurationRequest)(nil),  // 15: api.v1alpha1.insights.SetDefaultOutputConfigurationRequest
	(*GetDefaultOutputConfigurationRequest)(nil),  // 16: api.v1alpha1.insights.GetDefaultOutputConfigurationRequest
	(*CreateInsightResponse)(nil),                 // 17: api.v1alpha1.insights.CreateInsightResponse
	(*ListInsightsResponse)(nil),                  // 18: api.v1alpha1.insights.ListInsightsResponse
	(*ListInsightsStreamResponse)(nil),            // 19: api.v1alpha1.insights.ListInsightsStreamResponse
	(*ListOrgInsightsResponse)(nil),               // 20: api.v1alpha1.insights.ListOrgInsightsResponse
	(*UpdateInsightResponse)(nil),                 // 21: api.v1alpha1.insights.UpdateInsightResponse
	(*DeleteInsightResponse)(nil),                 // 22: api.v1alpha1.insights.DeleteInsightResponse
	(*GetInsightResponse)(nil),                    // 23: api.v1alpha1.insights.GetInsightResponse
	(*GetVfsSchemaResponse)(nil),                  // 24: api.v1alpha1.insights.GetVfsSchemaResponse
	(*ListVfsesResponse)(nil),                     // 25: api.v1alpha1.insights.ListVfsesResponse
	(*ListVfsSchemasResponse)(nil),                // 26: api.v1alpha1.insights.ListVfsSchemasResponse
	(*PublishInsightResponse)(nil),                // 27: api.v1alpha1.insights.PublishInsightResponse
	(*CreateOutputConfigurationResponse)(nil),     // 28: api.v1alpha1.insights.CreateOutputConfigurationResponse
	(*ListOutputConfigurationsResponse)(nil),      // 29: api.v1alpha1.insights.ListOutputConfigurationsResponse
	(*UpdateOutputConfigurationResponse)(nil),     // 30: api.v1alpha1.insights.UpdateOutputConfigurationResponse
	(*DeleteOutputConfigurationResponse)(nil),     // 31: api.v1alpha1.insights.DeleteOutputConfigurationResponse
	(*GetOutputConfigurationResponse)(nil),        // 32: api.v1alpha1.insights.GetOutputConfigurationResponse
	(*SetDefaultOutputConfigurationResponse)(nil), // 33: api.v1alpha1.insights.SetDefaultOutputConfigurationResponse
	(*GetDefaultOutputConfigurationResponse)(nil), // 34: api.v1alpha1.insights.GetDefaultOutputConfigurationResponse
}
var file_api_v1alpha1_insights_service_proto_depIdxs = []int32{
	0,  // 0: api.v1alpha1.insights.Insights.CreateInsight:input_type -> api.v1alpha1.insights.CreateInsightRequest
	1,  // 1: api.v1alpha1.insights.Insights.ListInsights:input_type -> api.v1alpha1.insights.ListInsightsRequest
	1,  // 2: api.v1alpha1.insights.Insights.ListInsightsStream:input_type -> api.v1alpha1.insights.ListInsightsRequest
	2,  // 3: api.v1alpha1.insights.Insights.ListOrgInsights:input_type -> api.v1alpha1.insights.ListOrgInsightsRequest
	3,  // 4: api.v1alpha1.insights.Insights.UpdateInsight:input_type -> api.v1alpha1.insights.UpdateInsightRequest
	4,  // 5: api.v1alpha1.insights.Insights.DeleteInsight:input_type -> api.v1alpha1.insights.DeleteInsightRequest
	5,  // 6: api.v1alpha1.insights.Insights.GetInsight:input_type -> api.v1alpha1.insights.GetInsightRequest
	0,  // 7: api.v1alpha1.insights.Insights.CreateCommonsInsight:input_type -> api.v1alpha1.insights.CreateInsightRequest
	3,  // 8: api.v1alpha1.insights.Insights.UpdateCommonsInsight:input_type -> api.v1alpha1.insights.UpdateInsightRequest
	4,  // 9: api.v1alpha1.insights.Insights.DeleteCommonsInsight:input_type -> api.v1alpha1.insights.DeleteInsightRequest
	6,  // 10: api.v1alpha1.insights.Insights.GetVfsSchema:input_type -> api.v1alpha1.insights.GetVfsSchemaRequest
	7,  // 11: api.v1alpha1.insights.Insights.ListVfses:input_type -> api.v1alpha1.insights.ListVfsesRequest
	8,  // 12: api.v1alpha1.insights.Insights.ListVfsSchemas:input_type -> api.v1alpha1.insights.ListVfsSchemasRequest
	9,  // 13: api.v1alpha1.insights.Insights.PublishInsight:input_type -> api.v1alpha1.insights.PublishInsightRequest
	10, // 14: api.v1alpha1.insights.Insights.CreateOutputConfiguration:input_type -> api.v1alpha1.insights.CreateOutputConfigurationRequest
	11, // 15: api.v1alpha1.insights.Insights.ListOutputConfigurations:input_type -> api.v1alpha1.insights.ListOutputConfigurationsRequest
	12, // 16: api.v1alpha1.insights.Insights.UpdateOutputConfiguration:input_type -> api.v1alpha1.insights.UpdateOutputConfigurationRequest
	13, // 17: api.v1alpha1.insights.Insights.DeleteOutputConfiguration:input_type -> api.v1alpha1.insights.DeleteOutputConfigurationRequest
	14, // 18: api.v1alpha1.insights.Insights.GetOutputConfiguration:input_type -> api.v1alpha1.insights.GetOutputConfigurationRequest
	15, // 19: api.v1alpha1.insights.Insights.SetDefaultOutputConfiguration:input_type -> api.v1alpha1.insights.SetDefaultOutputConfigurationRequest
	16, // 20: api.v1alpha1.insights.Insights.GetDefaultOutputConfiguration:input_type -> api.v1alpha1.insights.GetDefaultOutputConfigurationRequest
	17, // 21: api.v1alpha1.insights.Insights.CreateInsight:output_type -> api.v1alpha1.insights.CreateInsightResponse
	18, // 22: api.v1alpha1.insights.Insights.ListInsights:output_type -> api.v1alpha1.insights.ListInsightsResponse
	19, // 23: api.v1alpha1.insights.Insights.ListInsightsStream:output_type -> api.v1alpha1.insights.ListInsightsStreamResponse
	20, // 24: api.v1alpha1.insights.Insights.ListOrgInsights:output_type -> api.v1alpha1.insights.ListOrgInsightsResponse
	21, // 25: api.v1alpha1.insights.Insights.UpdateInsight:output_type -> api.v1alpha1.insights.UpdateInsightResponse
	22, // 26: api.v1alpha1.insights.Insights.DeleteInsight:output_type -> api.v1alpha1.insights.DeleteInsightResponse
	23, // 27: api.v1alpha1.insights.Insights.GetInsight:output_type -> api.v1alpha1.insights.GetInsightResponse
	17, // 28: api.v1alpha1.insights.Insights.CreateCommonsInsight:output_type -> api.v1alpha1.insights.CreateInsightResponse
	21, // 29: api.v1alpha1.insights.Insights.UpdateCommonsInsight:output_type -> api.v1alpha1.insights.UpdateInsightResponse
	22, // 30: api.v1alpha1.insights.Insights.DeleteCommonsInsight:output_type -> api.v1alpha1.insights.DeleteInsightResponse
	24, // 31: api.v1alpha1.insights.Insights.GetVfsSchema:output_type -> api.v1alpha1.insights.GetVfsSchemaResponse
	25, // 32: api.v1alpha1.insights.Insights.ListVfses:output_type -> api.v1alpha1.insights.ListVfsesResponse
	26, // 33: api.v1alpha1.insights.Insights.ListVfsSchemas:output_type -> api.v1alpha1.insights.ListVfsSchemasResponse
	27, // 34: api.v1alpha1.insights.Insights.PublishInsight:output_type -> api.v1alpha1.insights.PublishInsightResponse
	28, // 35: api.v1alpha1.insights.Insights.CreateOutputConfiguration:output_type -> api.v1alpha1.insights.CreateOutputConfigurationResponse
	29, // 36: api.v1alpha1.insights.Insights.ListOutputConfigurations:output_type -> api.v1alpha1.insights.ListOutputConfigurationsResponse
	30, // 37: api.v1alpha1.insights.Insights.UpdateOutputConfiguration:output_type -> api.v1alpha1.insights.UpdateOutputConfigurationResponse
	31, // 38: api.v1alpha1.insights.Insights.DeleteOutputConfiguration:output_type -> api.v1alpha1.insights.DeleteOutputConfigurationResponse
	32, // 39: api.v1alpha1.insights.Insights.GetOutputConfiguration:output_type -> api.v1alpha1.insights.GetOutputConfigurationResponse
	33, // 40: api.v1alpha1.insights.Insights.SetDefaultOutputConfiguration:output_type -> api.v1alpha1.insights.SetDefaultOutputConfigurationResponse
	34, // 41: api.v1alpha1.insights.Insights.GetDefaultOutputConfiguration:output_type -> api.v1alpha1.insights.GetDefaultOutputConfigurationResponse
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_insights_service_proto_init() }
func file_api_v1alpha1_insights_service_proto_init() {
	if File_api_v1alpha1_insights_service_proto != nil {
		return
	}
	file_api_v1alpha1_insights_insight_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1alpha1_insights_service_proto_rawDesc), len(file_api_v1alpha1_insights_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_insights_service_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_insights_service_proto_depIdxs,
	}.Build()
	File_api_v1alpha1_insights_service_proto = out.File
	file_api_v1alpha1_insights_service_proto_goTypes = nil
	file_api_v1alpha1_insights_service_proto_depIdxs = nil
}
