// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v0alpha/cfg.proto

package v0alpha

import (
	_ "github.com/tcncloud/api-go/annotations"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigReq) Reset() {
	*x = GetConfigReq{}
	mi := &file_api_v0alpha_cfg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReq) ProtoMessage() {}

func (x *GetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0alpha_cfg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReq.ProtoReflect.Descriptor instead.
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return file_api_v0alpha_cfg_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigReq) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

type WebAgent struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	OpenSips          *WebAgent_OpenSips       `protobuf:"bytes,1,opt,name=open_sips,json=openSips,proto3" json:"open_sips,omitempty"`
	EnginePriority    *WebAgent_EnginePriority `protobuf:"bytes,2,opt,name=engine_priority,json=enginePriority,proto3" json:"engine_priority,omitempty"`
	LogLevel          int64                    `protobuf:"varint,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	UseStun           int64                    `protobuf:"varint,4,opt,name=use_stun,json=useStun,proto3" json:"use_stun,omitempty"`
	UseFastStun       int64                    `protobuf:"varint,5,opt,name=use_fast_stun,json=useFastStun,proto3" json:"use_fast_stun,omitempty"`
	UseFastIce        int64                    `protobuf:"varint,6,opt,name=use_fast_ice,json=useFastIce,proto3" json:"use_fast_ice,omitempty"`
	IceTimeout        int64                    `protobuf:"varint,7,opt,name=ice_timeout,json=iceTimeout,proto3" json:"ice_timeout,omitempty"`
	SetFinalCodec     int64                    `protobuf:"varint,8,opt,name=set_final_codec,json=setFinalCodec,proto3" json:"set_final_codec,omitempty"`
	UseRport          int64                    `protobuf:"varint,9,opt,name=use_rport,json=useRport,proto3" json:"use_rport,omitempty"`
	Server            *WebAgent_Server         `protobuf:"bytes,10,opt,name=server,proto3" json:"server,omitempty"`
	BaseUrl           string                   `protobuf:"bytes,11,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	StunServerAddress string                   `protobuf:"bytes,12,opt,name=stun_server_address,json=stunServerAddress,proto3" json:"stun_server_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebAgent) Reset() {
	*x = WebAgent{}
	mi := &file_api_v0alpha_cfg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAgent) ProtoMessage() {}

func (x *WebAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0alpha_cfg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAgent.ProtoReflect.Descriptor instead.
func (*WebAgent) Descriptor() ([]byte, []int) {
	return file_api_v0alpha_cfg_proto_rawDescGZIP(), []int{1}
}

func (x *WebAgent) GetOpenSips() *WebAgent_OpenSips {
	if x != nil {
		return x.OpenSips
	}
	return nil
}

func (x *WebAgent) GetEnginePriority() *WebAgent_EnginePriority {
	if x != nil {
		return x.EnginePriority
	}
	return nil
}

func (x *WebAgent) GetLogLevel() int64 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *WebAgent) GetUseStun() int64 {
	if x != nil {
		return x.UseStun
	}
	return 0
}

func (x *WebAgent) GetUseFastStun() int64 {
	if x != nil {
		return x.UseFastStun
	}
	return 0
}

func (x *WebAgent) GetUseFastIce() int64 {
	if x != nil {
		return x.UseFastIce
	}
	return 0
}

func (x *WebAgent) GetIceTimeout() int64 {
	if x != nil {
		return x.IceTimeout
	}
	return 0
}

func (x *WebAgent) GetSetFinalCodec() int64 {
	if x != nil {
		return x.SetFinalCodec
	}
	return 0
}

func (x *WebAgent) GetUseRport() int64 {
	if x != nil {
		return x.UseRport
	}
	return 0
}

func (x *WebAgent) GetServer() *WebAgent_Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *WebAgent) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *WebAgent) GetStunServerAddress() string {
	if x != nil {
		return x.StunServerAddress
	}
	return ""
}

type WebAgent_OpenSips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAgent_OpenSips) Reset() {
	*x = WebAgent_OpenSips{}
	mi := &file_api_v0alpha_cfg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAgent_OpenSips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAgent_OpenSips) ProtoMessage() {}

func (x *WebAgent_OpenSips) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0alpha_cfg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAgent_OpenSips.ProtoReflect.Descriptor instead.
func (*WebAgent_OpenSips) Descriptor() ([]byte, []int) {
	return file_api_v0alpha_cfg_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WebAgent_OpenSips) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type WebAgent_EnginePriority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Java          int64                  `protobuf:"varint,1,opt,name=java,proto3" json:"java,omitempty"`
	Webrtc        int64                  `protobuf:"varint,2,opt,name=webrtc,proto3" json:"webrtc,omitempty"`
	Ns            int64                  `protobuf:"varint,3,opt,name=ns,proto3" json:"ns,omitempty"`
	Flash         int64                  `protobuf:"varint,4,opt,name=flash,proto3" json:"flash,omitempty"`
	App           int64                  `protobuf:"varint,5,opt,name=app,proto3" json:"app,omitempty"`
	P2P           int64                  `protobuf:"varint,6,opt,name=p2p,proto3" json:"p2p,omitempty"`
	AccessNum     int64                  `protobuf:"varint,7,opt,name=access_num,json=accessNum,proto3" json:"access_num,omitempty"`
	Native        int64                  `protobuf:"varint,8,opt,name=native,proto3" json:"native,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAgent_EnginePriority) Reset() {
	*x = WebAgent_EnginePriority{}
	mi := &file_api_v0alpha_cfg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAgent_EnginePriority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAgent_EnginePriority) ProtoMessage() {}

func (x *WebAgent_EnginePriority) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0alpha_cfg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAgent_EnginePriority.ProtoReflect.Descriptor instead.
func (*WebAgent_EnginePriority) Descriptor() ([]byte, []int) {
	return file_api_v0alpha_cfg_proto_rawDescGZIP(), []int{1, 1}
}

func (x *WebAgent_EnginePriority) GetJava() int64 {
	if x != nil {
		return x.Java
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetWebrtc() int64 {
	if x != nil {
		return x.Webrtc
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetNs() int64 {
	if x != nil {
		return x.Ns
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetFlash() int64 {
	if x != nil {
		return x.Flash
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetApp() int64 {
	if x != nil {
		return x.App
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetP2P() int64 {
	if x != nil {
		return x.P2P
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetAccessNum() int64 {
	if x != nil {
		return x.AccessNum
	}
	return 0
}

func (x *WebAgent_EnginePriority) GetNative() int64 {
	if x != nil {
		return x.Native
	}
	return 0
}

type WebAgent_Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sip           string                 `protobuf:"bytes,1,opt,name=sip,proto3" json:"sip,omitempty"`
	Webrtc        string                 `protobuf:"bytes,2,opt,name=webrtc,proto3" json:"webrtc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAgent_Server) Reset() {
	*x = WebAgent_Server{}
	mi := &file_api_v0alpha_cfg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAgent_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAgent_Server) ProtoMessage() {}

func (x *WebAgent_Server) ProtoReflect() protoreflect.Message {
	mi := &file_api_v0alpha_cfg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAgent_Server.ProtoReflect.Descriptor instead.
func (*WebAgent_Server) Descriptor() ([]byte, []int) {
	return file_api_v0alpha_cfg_proto_rawDescGZIP(), []int{1, 2}
}

func (x *WebAgent_Server) GetSip() string {
	if x != nil {
		return x.Sip
	}
	return ""
}

func (x *WebAgent_Server) GetWebrtc() string {
	if x != nil {
		return x.Webrtc
	}
	return ""
}

var File_api_v0alpha_cfg_proto protoreflect.FileDescriptor

const file_api_v0alpha_cfg_proto_rawDesc = "" +
	"\n" +
	"\x15api/v0alpha/cfg.proto\x12\vapi.v0alpha\x1a\x17annotations/authz.proto\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\fGetConfigReq\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\"\x95\x06\n" +
	"\bWebAgent\x12;\n" +
	"\topen_sips\x18\x01 \x01(\v2\x1e.api.v0alpha.WebAgent.OpenSipsR\bopenSips\x12M\n" +
	"\x0fengine_priority\x18\x02 \x01(\v2$.api.v0alpha.WebAgent.EnginePriorityR\x0eenginePriority\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\x03R\blogLevel\x12\x19\n" +
	"\buse_stun\x18\x04 \x01(\x03R\auseStun\x12\"\n" +
	"\ruse_fast_stun\x18\x05 \x01(\x03R\vuseFastStun\x12 \n" +
	"\fuse_fast_ice\x18\x06 \x01(\x03R\n" +
	"useFastIce\x12\x1f\n" +
	"\vice_timeout\x18\a \x01(\x03R\n" +
	"iceTimeout\x12&\n" +
	"\x0fset_final_codec\x18\b \x01(\x03R\rsetFinalCodec\x12\x1b\n" +
	"\tuse_rport\x18\t \x01(\x03R\buseRport\x124\n" +
	"\x06server\x18\n" +
	" \x01(\v2\x1c.api.v0alpha.WebAgent.ServerR\x06server\x12\x19\n" +
	"\bbase_url\x18\v \x01(\tR\abaseUrl\x12.\n" +
	"\x13stun_server_address\x18\f \x01(\tR\x11stunServerAddress\x1a$\n" +
	"\bOpenSips\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x1a\xbd\x01\n" +
	"\x0eEnginePriority\x12\x12\n" +
	"\x04java\x18\x01 \x01(\x03R\x04java\x12\x16\n" +
	"\x06webrtc\x18\x02 \x01(\x03R\x06webrtc\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\x03R\x02ns\x12\x14\n" +
	"\x05flash\x18\x04 \x01(\x03R\x05flash\x12\x10\n" +
	"\x03app\x18\x05 \x01(\x03R\x03app\x12\x10\n" +
	"\x03p2p\x18\x06 \x01(\x03R\x03p2p\x12\x1d\n" +
	"\n" +
	"access_num\x18\a \x01(\x03R\taccessNum\x12\x16\n" +
	"\x06native\x18\b \x01(\x03R\x06native\x1a2\n" +
	"\x06Server\x12\x10\n" +
	"\x03sip\x18\x01 \x01(\tR\x03sip\x12\x16\n" +
	"\x06webrtc\x18\x02 \x01(\tR\x06webrtc2\x82\x01\n" +
	"\x03Cfg\x12{\n" +
	"\x11GetWebAgentConfig\x12\x19.api.v0alpha.GetConfigReq\x1a\x15.api.v0alpha.WebAgent\"4\xba\xb8\x91\x02\x02\x18\x01\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v0alpha/cfg/getwebagentconfigB\x90\x01\n" +
	"\x0fcom.api.v0alphaB\bCfgProtoP\x01Z&github.com/tcncloud/api-go/api/v0alpha\xa2\x02\x03AVX\xaa\x02\vApi.V0alpha\xca\x02\vApi\\V0alpha\xe2\x02\x17Api\\V0alpha\\GPBMetadata\xea\x02\fApi::V0alphab\x06proto3"

var (
	file_api_v0alpha_cfg_proto_rawDescOnce sync.Once
	file_api_v0alpha_cfg_proto_rawDescData []byte
)

func file_api_v0alpha_cfg_proto_rawDescGZIP() []byte {
	file_api_v0alpha_cfg_proto_rawDescOnce.Do(func() {
		file_api_v0alpha_cfg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v0alpha_cfg_proto_rawDesc), len(file_api_v0alpha_cfg_proto_rawDesc)))
	})
	return file_api_v0alpha_cfg_proto_rawDescData
}

var file_api_v0alpha_cfg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v0alpha_cfg_proto_goTypes = []any{
	(*GetConfigReq)(nil),            // 0: api.v0alpha.GetConfigReq
	(*WebAgent)(nil),                // 1: api.v0alpha.WebAgent
	(*WebAgent_OpenSips)(nil),       // 2: api.v0alpha.WebAgent.OpenSips
	(*WebAgent_EnginePriority)(nil), // 3: api.v0alpha.WebAgent.EnginePriority
	(*WebAgent_Server)(nil),         // 4: api.v0alpha.WebAgent.Server
}
var file_api_v0alpha_cfg_proto_depIdxs = []int32{
	2, // 0: api.v0alpha.WebAgent.open_sips:type_name -> api.v0alpha.WebAgent.OpenSips
	3, // 1: api.v0alpha.WebAgent.engine_priority:type_name -> api.v0alpha.WebAgent.EnginePriority
	4, // 2: api.v0alpha.WebAgent.server:type_name -> api.v0alpha.WebAgent.Server
	0, // 3: api.v0alpha.Cfg.GetWebAgentConfig:input_type -> api.v0alpha.GetConfigReq
	1, // 4: api.v0alpha.Cfg.GetWebAgentConfig:output_type -> api.v0alpha.WebAgent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v0alpha_cfg_proto_init() }
func file_api_v0alpha_cfg_proto_init() {
	if File_api_v0alpha_cfg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v0alpha_cfg_proto_rawDesc), len(file_api_v0alpha_cfg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v0alpha_cfg_proto_goTypes,
		DependencyIndexes: file_api_v0alpha_cfg_proto_depIdxs,
		MessageInfos:      file_api_v0alpha_cfg_proto_msgTypes,
	}.Build()
	File_api_v0alpha_cfg_proto = out.File
	file_api_v0alpha_cfg_proto_goTypes = nil
	file_api_v0alpha_cfg_proto_depIdxs = nil
}
