// Copyright (c) 2020, TCN Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1alpha1/workflows/service.proto

package workflowsconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	workflows "github.com/tcncloud/api-go/api/v1alpha1/workflows"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// FlowDefinitionPersistServiceName is the fully-qualified name of the FlowDefinitionPersistService
	// service.
	FlowDefinitionPersistServiceName = "api.v1alpha1.workflows.FlowDefinitionPersistService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FlowDefinitionPersistServiceCreateFlowDefinitionProcedure is the fully-qualified name of the
	// FlowDefinitionPersistService's CreateFlowDefinition RPC.
	FlowDefinitionPersistServiceCreateFlowDefinitionProcedure = "/api.v1alpha1.workflows.FlowDefinitionPersistService/CreateFlowDefinition"
	// FlowDefinitionPersistServiceGetFlowDefinitionProcedure is the fully-qualified name of the
	// FlowDefinitionPersistService's GetFlowDefinition RPC.
	FlowDefinitionPersistServiceGetFlowDefinitionProcedure = "/api.v1alpha1.workflows.FlowDefinitionPersistService/GetFlowDefinition"
	// FlowDefinitionPersistServiceListFlowDefinitionsProcedure is the fully-qualified name of the
	// FlowDefinitionPersistService's ListFlowDefinitions RPC.
	FlowDefinitionPersistServiceListFlowDefinitionsProcedure = "/api.v1alpha1.workflows.FlowDefinitionPersistService/ListFlowDefinitions"
	// FlowDefinitionPersistServiceUpdateFlowDefinitionProcedure is the fully-qualified name of the
	// FlowDefinitionPersistService's UpdateFlowDefinition RPC.
	FlowDefinitionPersistServiceUpdateFlowDefinitionProcedure = "/api.v1alpha1.workflows.FlowDefinitionPersistService/UpdateFlowDefinition"
	// FlowDefinitionPersistServiceValidateFlowDefinitionProcedure is the fully-qualified name of the
	// FlowDefinitionPersistService's ValidateFlowDefinition RPC.
	FlowDefinitionPersistServiceValidateFlowDefinitionProcedure = "/api.v1alpha1.workflows.FlowDefinitionPersistService/ValidateFlowDefinition"
)

// FlowDefinitionPersistServiceClient is a client for the
// api.v1alpha1.workflows.FlowDefinitionPersistService service.
type FlowDefinitionPersistServiceClient interface {
	// CreateFlowDefinition creates a new flow definition in the database
	CreateFlowDefinition(context.Context, *connect_go.Request[workflows.CreateFlowDefinitionRequest]) (*connect_go.Response[workflows.CreateFlowDefinitionResponse], error)
	// GetFlowDefinition retrieves a flow definition from the database
	GetFlowDefinition(context.Context, *connect_go.Request[workflows.GetFlowDefinitionRequest]) (*connect_go.Response[workflows.GetFlowDefinitionResponse], error)
	// ListFlowDefinitions retrieves a list of flow definitions from the database optionally filtered by the owning application
	// if application is not specified, all flow definitions for the org are returned
	ListFlowDefinitions(context.Context, *connect_go.Request[workflows.ListFlowDefinitionsRequest]) (*connect_go.ServerStreamForClient[workflows.ListFlowDefinitionsResponse], error)
	// UpdateFlowDefinition updates a flow definition in the database. Only the name, description and definition graph itself are updated
	UpdateFlowDefinition(context.Context, *connect_go.Request[workflows.UpdateFlowDefinitionRequest]) (*connect_go.Response[workflows.UpdateFlowDefinitionResponse], error)
	// ValidateFlowDefinition validates a flow definition in the database. Only the name, description and definition graph itself are updated
	ValidateFlowDefinition(context.Context, *connect_go.Request[workflows.ValidateFlowDefinitionRequest]) (*connect_go.Response[workflows.ValidateFlowDefinitionResponse], error)
}

// NewFlowDefinitionPersistServiceClient constructs a client for the
// api.v1alpha1.workflows.FlowDefinitionPersistService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFlowDefinitionPersistServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) FlowDefinitionPersistServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &flowDefinitionPersistServiceClient{
		createFlowDefinition: connect_go.NewClient[workflows.CreateFlowDefinitionRequest, workflows.CreateFlowDefinitionResponse](
			httpClient,
			baseURL+FlowDefinitionPersistServiceCreateFlowDefinitionProcedure,
			opts...,
		),
		getFlowDefinition: connect_go.NewClient[workflows.GetFlowDefinitionRequest, workflows.GetFlowDefinitionResponse](
			httpClient,
			baseURL+FlowDefinitionPersistServiceGetFlowDefinitionProcedure,
			opts...,
		),
		listFlowDefinitions: connect_go.NewClient[workflows.ListFlowDefinitionsRequest, workflows.ListFlowDefinitionsResponse](
			httpClient,
			baseURL+FlowDefinitionPersistServiceListFlowDefinitionsProcedure,
			opts...,
		),
		updateFlowDefinition: connect_go.NewClient[workflows.UpdateFlowDefinitionRequest, workflows.UpdateFlowDefinitionResponse](
			httpClient,
			baseURL+FlowDefinitionPersistServiceUpdateFlowDefinitionProcedure,
			opts...,
		),
		validateFlowDefinition: connect_go.NewClient[workflows.ValidateFlowDefinitionRequest, workflows.ValidateFlowDefinitionResponse](
			httpClient,
			baseURL+FlowDefinitionPersistServiceValidateFlowDefinitionProcedure,
			opts...,
		),
	}
}

// flowDefinitionPersistServiceClient implements FlowDefinitionPersistServiceClient.
type flowDefinitionPersistServiceClient struct {
	createFlowDefinition   *connect_go.Client[workflows.CreateFlowDefinitionRequest, workflows.CreateFlowDefinitionResponse]
	getFlowDefinition      *connect_go.Client[workflows.GetFlowDefinitionRequest, workflows.GetFlowDefinitionResponse]
	listFlowDefinitions    *connect_go.Client[workflows.ListFlowDefinitionsRequest, workflows.ListFlowDefinitionsResponse]
	updateFlowDefinition   *connect_go.Client[workflows.UpdateFlowDefinitionRequest, workflows.UpdateFlowDefinitionResponse]
	validateFlowDefinition *connect_go.Client[workflows.ValidateFlowDefinitionRequest, workflows.ValidateFlowDefinitionResponse]
}

// CreateFlowDefinition calls
// api.v1alpha1.workflows.FlowDefinitionPersistService.CreateFlowDefinition.
func (c *flowDefinitionPersistServiceClient) CreateFlowDefinition(ctx context.Context, req *connect_go.Request[workflows.CreateFlowDefinitionRequest]) (*connect_go.Response[workflows.CreateFlowDefinitionResponse], error) {
	return c.createFlowDefinition.CallUnary(ctx, req)
}

// GetFlowDefinition calls api.v1alpha1.workflows.FlowDefinitionPersistService.GetFlowDefinition.
func (c *flowDefinitionPersistServiceClient) GetFlowDefinition(ctx context.Context, req *connect_go.Request[workflows.GetFlowDefinitionRequest]) (*connect_go.Response[workflows.GetFlowDefinitionResponse], error) {
	return c.getFlowDefinition.CallUnary(ctx, req)
}

// ListFlowDefinitions calls
// api.v1alpha1.workflows.FlowDefinitionPersistService.ListFlowDefinitions.
func (c *flowDefinitionPersistServiceClient) ListFlowDefinitions(ctx context.Context, req *connect_go.Request[workflows.ListFlowDefinitionsRequest]) (*connect_go.ServerStreamForClient[workflows.ListFlowDefinitionsResponse], error) {
	return c.listFlowDefinitions.CallServerStream(ctx, req)
}

// UpdateFlowDefinition calls
// api.v1alpha1.workflows.FlowDefinitionPersistService.UpdateFlowDefinition.
func (c *flowDefinitionPersistServiceClient) UpdateFlowDefinition(ctx context.Context, req *connect_go.Request[workflows.UpdateFlowDefinitionRequest]) (*connect_go.Response[workflows.UpdateFlowDefinitionResponse], error) {
	return c.updateFlowDefinition.CallUnary(ctx, req)
}

// ValidateFlowDefinition calls
// api.v1alpha1.workflows.FlowDefinitionPersistService.ValidateFlowDefinition.
func (c *flowDefinitionPersistServiceClient) ValidateFlowDefinition(ctx context.Context, req *connect_go.Request[workflows.ValidateFlowDefinitionRequest]) (*connect_go.Response[workflows.ValidateFlowDefinitionResponse], error) {
	return c.validateFlowDefinition.CallUnary(ctx, req)
}

// FlowDefinitionPersistServiceHandler is an implementation of the
// api.v1alpha1.workflows.FlowDefinitionPersistService service.
type FlowDefinitionPersistServiceHandler interface {
	// CreateFlowDefinition creates a new flow definition in the database
	CreateFlowDefinition(context.Context, *connect_go.Request[workflows.CreateFlowDefinitionRequest]) (*connect_go.Response[workflows.CreateFlowDefinitionResponse], error)
	// GetFlowDefinition retrieves a flow definition from the database
	GetFlowDefinition(context.Context, *connect_go.Request[workflows.GetFlowDefinitionRequest]) (*connect_go.Response[workflows.GetFlowDefinitionResponse], error)
	// ListFlowDefinitions retrieves a list of flow definitions from the database optionally filtered by the owning application
	// if application is not specified, all flow definitions for the org are returned
	ListFlowDefinitions(context.Context, *connect_go.Request[workflows.ListFlowDefinitionsRequest], *connect_go.ServerStream[workflows.ListFlowDefinitionsResponse]) error
	// UpdateFlowDefinition updates a flow definition in the database. Only the name, description and definition graph itself are updated
	UpdateFlowDefinition(context.Context, *connect_go.Request[workflows.UpdateFlowDefinitionRequest]) (*connect_go.Response[workflows.UpdateFlowDefinitionResponse], error)
	// ValidateFlowDefinition validates a flow definition in the database. Only the name, description and definition graph itself are updated
	ValidateFlowDefinition(context.Context, *connect_go.Request[workflows.ValidateFlowDefinitionRequest]) (*connect_go.Response[workflows.ValidateFlowDefinitionResponse], error)
}

// NewFlowDefinitionPersistServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFlowDefinitionPersistServiceHandler(svc FlowDefinitionPersistServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	flowDefinitionPersistServiceCreateFlowDefinitionHandler := connect_go.NewUnaryHandler(
		FlowDefinitionPersistServiceCreateFlowDefinitionProcedure,
		svc.CreateFlowDefinition,
		opts...,
	)
	flowDefinitionPersistServiceGetFlowDefinitionHandler := connect_go.NewUnaryHandler(
		FlowDefinitionPersistServiceGetFlowDefinitionProcedure,
		svc.GetFlowDefinition,
		opts...,
	)
	flowDefinitionPersistServiceListFlowDefinitionsHandler := connect_go.NewServerStreamHandler(
		FlowDefinitionPersistServiceListFlowDefinitionsProcedure,
		svc.ListFlowDefinitions,
		opts...,
	)
	flowDefinitionPersistServiceUpdateFlowDefinitionHandler := connect_go.NewUnaryHandler(
		FlowDefinitionPersistServiceUpdateFlowDefinitionProcedure,
		svc.UpdateFlowDefinition,
		opts...,
	)
	flowDefinitionPersistServiceValidateFlowDefinitionHandler := connect_go.NewUnaryHandler(
		FlowDefinitionPersistServiceValidateFlowDefinitionProcedure,
		svc.ValidateFlowDefinition,
		opts...,
	)
	return "/api.v1alpha1.workflows.FlowDefinitionPersistService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FlowDefinitionPersistServiceCreateFlowDefinitionProcedure:
			flowDefinitionPersistServiceCreateFlowDefinitionHandler.ServeHTTP(w, r)
		case FlowDefinitionPersistServiceGetFlowDefinitionProcedure:
			flowDefinitionPersistServiceGetFlowDefinitionHandler.ServeHTTP(w, r)
		case FlowDefinitionPersistServiceListFlowDefinitionsProcedure:
			flowDefinitionPersistServiceListFlowDefinitionsHandler.ServeHTTP(w, r)
		case FlowDefinitionPersistServiceUpdateFlowDefinitionProcedure:
			flowDefinitionPersistServiceUpdateFlowDefinitionHandler.ServeHTTP(w, r)
		case FlowDefinitionPersistServiceValidateFlowDefinitionProcedure:
			flowDefinitionPersistServiceValidateFlowDefinitionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFlowDefinitionPersistServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFlowDefinitionPersistServiceHandler struct{}

func (UnimplementedFlowDefinitionPersistServiceHandler) CreateFlowDefinition(context.Context, *connect_go.Request[workflows.CreateFlowDefinitionRequest]) (*connect_go.Response[workflows.CreateFlowDefinitionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1alpha1.workflows.FlowDefinitionPersistService.CreateFlowDefinition is not implemented"))
}

func (UnimplementedFlowDefinitionPersistServiceHandler) GetFlowDefinition(context.Context, *connect_go.Request[workflows.GetFlowDefinitionRequest]) (*connect_go.Response[workflows.GetFlowDefinitionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1alpha1.workflows.FlowDefinitionPersistService.GetFlowDefinition is not implemented"))
}

func (UnimplementedFlowDefinitionPersistServiceHandler) ListFlowDefinitions(context.Context, *connect_go.Request[workflows.ListFlowDefinitionsRequest], *connect_go.ServerStream[workflows.ListFlowDefinitionsResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1alpha1.workflows.FlowDefinitionPersistService.ListFlowDefinitions is not implemented"))
}

func (UnimplementedFlowDefinitionPersistServiceHandler) UpdateFlowDefinition(context.Context, *connect_go.Request[workflows.UpdateFlowDefinitionRequest]) (*connect_go.Response[workflows.UpdateFlowDefinitionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1alpha1.workflows.FlowDefinitionPersistService.UpdateFlowDefinition is not implemented"))
}

func (UnimplementedFlowDefinitionPersistServiceHandler) ValidateFlowDefinition(context.Context, *connect_go.Request[workflows.ValidateFlowDefinitionRequest]) (*connect_go.Response[workflows.ValidateFlowDefinitionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1alpha1.workflows.FlowDefinitionPersistService.ValidateFlowDefinition is not implemented"))
}
